package main

const (
	emptyBody             = "empty body"
	mutateMethod          = "/mutate"
	invalidContentType    = "invalid Content-Type=%v, expect \"application/json\""
	couldNotEncodeReview  = "could not encode response: %v"
	couldNotWriteReview   = "could not write response: %v"
	deployment            = "Deployment"
	pod                   = "Pod"
	nsmAnnotationKey      = "ns.networkservicemesh.io"
	securityAnnotationKey = "security.networkservicemesh.io"
	repoEnv               = "REPO"
	initContainerEnv      = "INITCONTAINER"
	tagEnv                = "TAG"
	jaegerHostEnv         = "JAEGER_AGENT_HOST"
	jaegerPortEnv         = "JAEGER_AGENT_PORT"
	repoDefault           = "networkservicemesh"
	initContainerDefault  = "nsm-init"
	tagDefault            = "latest"
	initContainerName     = "nsm-init-container"
	pathDeploymentSpec    = "/spec/template/spec"
	pathPodSpec           = "/spec"
	spireSocketVolume     = "spire-agent-socket"
	spireSocketPath       = "/run/spire/sockets"
	certFile              = "/etc/webhook/certs/cert.pem"
	keyFile               = "/etc/webhook/certs/key.pem"
)
