---
extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'

rules:
  truthy: disable
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  comments-indentation:
    ignore: .circleci/config.yml

ignore: scripts/aws/aws-k8s-cni.yaml
