// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nseconnect.proto

package nseconnect

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/ligato/networkservicemesh/pkg/nsm/apis/common"
	netmesh "github.com/ligato/networkservicemesh/pkg/nsm/apis/netmesh"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConnectRequest is sent
type ConnectRequest struct {
	RequestId            string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NetworkServiceName   string                   `protobuf:"bytes,2,opt,name=network_service_name,json=networkServiceName,proto3" json:"network_service_name,omitempty"`
	Context              map[string]string        `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Mechanisms           []*common.LocalMechanism `protobuf:"bytes,4,rep,name=mechanisms,proto3" json:"mechanisms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{0}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ConnectRequest) GetNetworkServiceName() string {
	if m != nil {
		return m.NetworkServiceName
	}
	return ""
}

func (m *ConnectRequest) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *ConnectRequest) GetMechanisms() []*common.LocalMechanism {
	if m != nil {
		return m.Mechanisms
	}
	return nil
}

// EndpointConnectionReply is sent back by NSE to NSM with information required for
// dataplane programming.
type ConnectReply struct {
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Mechanism            *common.LocalMechanism `protobuf:"bytes,2,opt,name=mechanism,proto3" json:"mechanism,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConnectReply) Reset()         { *m = ConnectReply{} }
func (m *ConnectReply) String() string { return proto.CompactTextString(m) }
func (*ConnectReply) ProtoMessage()    {}
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{1}
}

func (m *ConnectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReply.Unmarshal(m, b)
}
func (m *ConnectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReply.Marshal(b, m, deterministic)
}
func (m *ConnectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReply.Merge(m, src)
}
func (m *ConnectReply) XXX_Size() int {
	return xxx_messageInfo_ConnectReply.Size(m)
}
func (m *ConnectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReply proto.InternalMessageInfo

func (m *ConnectReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ConnectReply) GetMechanism() *common.LocalMechanism {
	if m != nil {
		return m.Mechanism
	}
	return nil
}

// EndpointConnectionInterface is sent by a NSM to NSE to inform NSE about
// the interface name which was created by the dataplane controller.
type EndpointConnectionMechanism struct {
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	LocalMechanism       *common.LocalMechanism `protobuf:"bytes,2,opt,name=local_mechanism,json=localMechanism,proto3" json:"local_mechanism,omitempty"`
	NetworkServiceName   string                 `protobuf:"bytes,3,opt,name=network_service_name,json=networkServiceName,proto3" json:"network_service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EndpointConnectionMechanism) Reset()         { *m = EndpointConnectionMechanism{} }
func (m *EndpointConnectionMechanism) String() string { return proto.CompactTextString(m) }
func (*EndpointConnectionMechanism) ProtoMessage()    {}
func (*EndpointConnectionMechanism) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{2}
}

func (m *EndpointConnectionMechanism) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointConnectionMechanism.Unmarshal(m, b)
}
func (m *EndpointConnectionMechanism) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointConnectionMechanism.Marshal(b, m, deterministic)
}
func (m *EndpointConnectionMechanism) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointConnectionMechanism.Merge(m, src)
}
func (m *EndpointConnectionMechanism) XXX_Size() int {
	return xxx_messageInfo_EndpointConnectionMechanism.Size(m)
}
func (m *EndpointConnectionMechanism) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointConnectionMechanism.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointConnectionMechanism proto.InternalMessageInfo

func (m *EndpointConnectionMechanism) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointConnectionMechanism) GetLocalMechanism() *common.LocalMechanism {
	if m != nil {
		return m.LocalMechanism
	}
	return nil
}

func (m *EndpointConnectionMechanism) GetNetworkServiceName() string {
	if m != nil {
		return m.NetworkServiceName
	}
	return ""
}

// EndpointConnectionInterfaceReply is sent back by NSE to NSM to confirm the presence
// of the programmed interface.
type EndpointConnectionMechanismReply struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MechanismFound       bool     `protobuf:"varint,2,opt,name=mechanism_found,json=mechanismFound,proto3" json:"mechanism_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointConnectionMechanismReply) Reset()         { *m = EndpointConnectionMechanismReply{} }
func (m *EndpointConnectionMechanismReply) String() string { return proto.CompactTextString(m) }
func (*EndpointConnectionMechanismReply) ProtoMessage()    {}
func (*EndpointConnectionMechanismReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{3}
}

func (m *EndpointConnectionMechanismReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointConnectionMechanismReply.Unmarshal(m, b)
}
func (m *EndpointConnectionMechanismReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointConnectionMechanismReply.Marshal(b, m, deterministic)
}
func (m *EndpointConnectionMechanismReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointConnectionMechanismReply.Merge(m, src)
}
func (m *EndpointConnectionMechanismReply) XXX_Size() int {
	return xxx_messageInfo_EndpointConnectionMechanismReply.Size(m)
}
func (m *EndpointConnectionMechanismReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointConnectionMechanismReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointConnectionMechanismReply proto.InternalMessageInfo

func (m *EndpointConnectionMechanismReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointConnectionMechanismReply) GetMechanismFound() bool {
	if m != nil {
		return m.MechanismFound
	}
	return false
}

type EndpointAdvertiseRequest struct {
	RequestId            string                          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NetworkEndpoint      *netmesh.NetworkServiceEndpoint `protobuf:"bytes,2,opt,name=network_endpoint,json=networkEndpoint,proto3" json:"network_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EndpointAdvertiseRequest) Reset()         { *m = EndpointAdvertiseRequest{} }
func (m *EndpointAdvertiseRequest) String() string { return proto.CompactTextString(m) }
func (*EndpointAdvertiseRequest) ProtoMessage()    {}
func (*EndpointAdvertiseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{4}
}

func (m *EndpointAdvertiseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointAdvertiseRequest.Unmarshal(m, b)
}
func (m *EndpointAdvertiseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointAdvertiseRequest.Marshal(b, m, deterministic)
}
func (m *EndpointAdvertiseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointAdvertiseRequest.Merge(m, src)
}
func (m *EndpointAdvertiseRequest) XXX_Size() int {
	return xxx_messageInfo_EndpointAdvertiseRequest.Size(m)
}
func (m *EndpointAdvertiseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointAdvertiseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointAdvertiseRequest proto.InternalMessageInfo

func (m *EndpointAdvertiseRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointAdvertiseRequest) GetNetworkEndpoint() *netmesh.NetworkServiceEndpoint {
	if m != nil {
		return m.NetworkEndpoint
	}
	return nil
}

type EndpointAdvertiseReply struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accepted             bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AdmissionError       string   `protobuf:"bytes,3,opt,name=admission_error,json=admissionError,proto3" json:"admission_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointAdvertiseReply) Reset()         { *m = EndpointAdvertiseReply{} }
func (m *EndpointAdvertiseReply) String() string { return proto.CompactTextString(m) }
func (*EndpointAdvertiseReply) ProtoMessage()    {}
func (*EndpointAdvertiseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{5}
}

func (m *EndpointAdvertiseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointAdvertiseReply.Unmarshal(m, b)
}
func (m *EndpointAdvertiseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointAdvertiseReply.Marshal(b, m, deterministic)
}
func (m *EndpointAdvertiseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointAdvertiseReply.Merge(m, src)
}
func (m *EndpointAdvertiseReply) XXX_Size() int {
	return xxx_messageInfo_EndpointAdvertiseReply.Size(m)
}
func (m *EndpointAdvertiseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointAdvertiseReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointAdvertiseReply proto.InternalMessageInfo

func (m *EndpointAdvertiseReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointAdvertiseReply) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *EndpointAdvertiseReply) GetAdmissionError() string {
	if m != nil {
		return m.AdmissionError
	}
	return ""
}

// Message sent by NSE to NSM informing of a removal previously advertised
// endpoint. NSM will attempt to locate Customer Resource and delete it.
//
type EndpointRemoveRequest struct {
	RequestId            string                          `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NetworkEndpoint      *netmesh.NetworkServiceEndpoint `protobuf:"bytes,2,opt,name=network_endpoint,json=networkEndpoint,proto3" json:"network_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *EndpointRemoveRequest) Reset()         { *m = EndpointRemoveRequest{} }
func (m *EndpointRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*EndpointRemoveRequest) ProtoMessage()    {}
func (*EndpointRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{6}
}

func (m *EndpointRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointRemoveRequest.Unmarshal(m, b)
}
func (m *EndpointRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointRemoveRequest.Marshal(b, m, deterministic)
}
func (m *EndpointRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointRemoveRequest.Merge(m, src)
}
func (m *EndpointRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_EndpointRemoveRequest.Size(m)
}
func (m *EndpointRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointRemoveRequest proto.InternalMessageInfo

func (m *EndpointRemoveRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointRemoveRequest) GetNetworkEndpoint() *netmesh.NetworkServiceEndpoint {
	if m != nil {
		return m.NetworkEndpoint
	}
	return nil
}

type EndpointRemoveReply struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accepted             bool     `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	AdmissionError       string   `protobuf:"bytes,3,opt,name=admission_error,json=admissionError,proto3" json:"admission_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndpointRemoveReply) Reset()         { *m = EndpointRemoveReply{} }
func (m *EndpointRemoveReply) String() string { return proto.CompactTextString(m) }
func (*EndpointRemoveReply) ProtoMessage()    {}
func (*EndpointRemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e33aba36f437ad2, []int{7}
}

func (m *EndpointRemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointRemoveReply.Unmarshal(m, b)
}
func (m *EndpointRemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointRemoveReply.Marshal(b, m, deterministic)
}
func (m *EndpointRemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointRemoveReply.Merge(m, src)
}
func (m *EndpointRemoveReply) XXX_Size() int {
	return xxx_messageInfo_EndpointRemoveReply.Size(m)
}
func (m *EndpointRemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointRemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointRemoveReply proto.InternalMessageInfo

func (m *EndpointRemoveReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *EndpointRemoveReply) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *EndpointRemoveReply) GetAdmissionError() string {
	if m != nil {
		return m.AdmissionError
	}
	return ""
}

func init() {
	proto.RegisterType((*ConnectRequest)(nil), "nseconnect.ConnectRequest")
	proto.RegisterMapType((map[string]string)(nil), "nseconnect.ConnectRequest.ContextEntry")
	proto.RegisterType((*ConnectReply)(nil), "nseconnect.ConnectReply")
	proto.RegisterType((*EndpointConnectionMechanism)(nil), "nseconnect.EndpointConnectionMechanism")
	proto.RegisterType((*EndpointConnectionMechanismReply)(nil), "nseconnect.EndpointConnectionMechanismReply")
	proto.RegisterType((*EndpointAdvertiseRequest)(nil), "nseconnect.EndpointAdvertiseRequest")
	proto.RegisterType((*EndpointAdvertiseReply)(nil), "nseconnect.EndpointAdvertiseReply")
	proto.RegisterType((*EndpointRemoveRequest)(nil), "nseconnect.EndpointRemoveRequest")
	proto.RegisterType((*EndpointRemoveReply)(nil), "nseconnect.EndpointRemoveReply")
}

func init() { proto.RegisterFile("nseconnect.proto", fileDescriptor_7e33aba36f437ad2) }

var fileDescriptor_7e33aba36f437ad2 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0xad, 0xba, 0xdb, 0xab, 0xb4, 0x75, 0x5c, 0x4b, 0x88, 0xc8, 0xd6, 0x20, 0xec, 0x3e,
	0xb5, 0x52, 0x45, 0x64, 0x5f, 0x96, 0x45, 0xaa, 0x28, 0xba, 0x42, 0xf4, 0xc5, 0x07, 0x09, 0xd9,
	0xc9, 0xb5, 0x1d, 0x9b, 0x99, 0x89, 0x99, 0x69, 0x35, 0xe0, 0x93, 0xe0, 0x3f, 0xf8, 0x17, 0x7e,
	0x87, 0x7f, 0x25, 0x49, 0x26, 0xd9, 0x56, 0x9a, 0x6d, 0x7d, 0x71, 0x9f, 0x92, 0x39, 0xf7, 0xce,
	0x39, 0xe7, 0x9e, 0x99, 0x04, 0xba, 0x42, 0x21, 0x95, 0x42, 0x20, 0xd5, 0x83, 0x38, 0x91, 0x5a,
	0x12, 0x38, 0x47, 0x9c, 0xe7, 0x13, 0xa6, 0xa7, 0xf3, 0xb3, 0x01, 0x95, 0x7c, 0x18, 0xb1, 0x49,
	0xa0, 0xe5, 0x50, 0xa0, 0xfe, 0x22, 0x93, 0x99, 0xc2, 0x64, 0xc1, 0x28, 0x72, 0x54, 0xd3, 0x61,
	0x3c, 0x9b, 0x0c, 0x85, 0xe2, 0xc3, 0x20, 0x66, 0x2a, 0xab, 0xe7, 0xa0, 0x79, 0x16, 0xa4, 0xce,
	0xf8, 0xdf, 0x89, 0xa8, 0xe4, 0x5c, 0x0a, 0xf3, 0x28, 0x68, 0xdc, 0x9f, 0x0d, 0x68, 0x3f, 0x2d,
	0xbc, 0x79, 0xf8, 0x79, 0x8e, 0x4a, 0x93, 0xbb, 0x00, 0x49, 0xf1, 0xea, 0xb3, 0xd0, 0xb6, 0xfa,
	0xd6, 0x61, 0xcb, 0x6b, 0x19, 0xe4, 0x45, 0x48, 0x1e, 0xc0, 0x9e, 0x11, 0xf2, 0x8d, 0x92, 0x2f,
	0x02, 0x8e, 0x76, 0x23, 0x6f, 0x24, 0xa6, 0xf6, 0xb6, 0x28, 0x9d, 0x06, 0x1c, 0xc9, 0x09, 0xec,
	0x50, 0x29, 0x34, 0x7e, 0xd5, 0x76, 0xb3, 0xdf, 0x3c, 0xbc, 0x3e, 0x3a, 0x18, 0x2c, 0x65, 0xb4,
	0xaa, 0x9e, 0x2d, 0xb3, 0xce, 0xb1, 0xd0, 0x49, 0xea, 0x95, 0xfb, 0xc8, 0x63, 0x00, 0x8e, 0x74,
	0x1a, 0x08, 0xa6, 0xb8, 0xb2, 0xaf, 0xe4, 0x2c, 0xbd, 0x81, 0x99, 0xe4, 0x95, 0xa4, 0x41, 0xf4,
	0xba, 0x2c, 0x7b, 0x4b, 0x9d, 0xce, 0x11, 0xdc, 0x58, 0x26, 0x24, 0x5d, 0x68, 0xce, 0x30, 0x35,
	0x43, 0x65, 0xaf, 0x64, 0x0f, 0xae, 0x2e, 0x82, 0x68, 0x5e, 0xfa, 0x2f, 0x16, 0x47, 0x8d, 0x27,
	0x96, 0x4b, 0xf3, 0xbd, 0x85, 0xb7, 0x38, 0x4a, 0x37, 0xe5, 0xf2, 0x08, 0x5a, 0x95, 0x70, 0x4e,
	0x56, 0xef, 0xf0, 0xbc, 0xd1, 0xfd, 0x65, 0xc1, 0x9d, 0xb1, 0x08, 0x63, 0xc9, 0x84, 0x36, 0x6a,
	0x4c, 0x8a, 0xaa, 0x75, 0x93, 0xe8, 0x31, 0x74, 0xa2, 0x8c, 0xdb, 0xdf, 0x56, 0xba, 0x1d, 0xad,
	0xac, 0x6b, 0x4f, 0xb3, 0x59, 0x77, 0x9a, 0xee, 0x27, 0xe8, 0x5f, 0x60, 0x78, 0xab, 0xa8, 0x0e,
	0xa0, 0x53, 0xf9, 0xf5, 0x3f, 0xca, 0xb9, 0x08, 0x73, 0xd7, 0xbb, 0x5e, 0xbb, 0x82, 0x9f, 0x65,
	0xa8, 0xfb, 0xc3, 0x02, 0xbb, 0x14, 0x3b, 0x09, 0x17, 0x98, 0x68, 0xa6, 0x70, 0xcb, 0x7b, 0xfa,
	0x12, 0xba, 0xe5, 0x64, 0x68, 0x28, 0x4c, 0x36, 0xfb, 0x83, 0xf2, 0x53, 0x3a, 0x5d, 0x19, 0xaf,
	0x54, 0xf2, 0x3a, 0x66, 0x63, 0x09, 0xb8, 0xdf, 0xa0, 0xb7, 0xc6, 0xc6, 0x16, 0x93, 0x3a, 0xb0,
	0x1b, 0x50, 0x8a, 0xb1, 0xc6, 0x72, 0xc4, 0x6a, 0x9d, 0xa5, 0x10, 0x84, 0x9c, 0x29, 0xc5, 0xa4,
	0xf0, 0x31, 0x49, 0x64, 0x62, 0x52, 0x6f, 0x57, 0xf0, 0x38, 0x43, 0xdd, 0xef, 0x16, 0xdc, 0xae,
	0xbc, 0x21, 0x97, 0x8b, 0xcb, 0x88, 0x20, 0x85, 0x5b, 0x7f, 0x7b, 0xf8, 0x4f, 0xf3, 0x8f, 0xde,
	0x43, 0x6f, 0xbd, 0x4b, 0x72, 0x0c, 0x3b, 0xe6, 0x0e, 0x12, 0xa7, 0xfe, 0x9f, 0xe2, 0xd8, 0x6b,
	0x6b, 0x71, 0x94, 0x8e, 0x7e, 0x5b, 0x40, 0x4a, 0xb6, 0x37, 0x31, 0x26, 0x41, 0x76, 0x99, 0x15,
	0xf9, 0x00, 0x37, 0xab, 0x73, 0xae, 0xc4, 0xee, 0x2f, 0xb3, 0xd4, 0xdd, 0x4a, 0xc7, 0xdd, 0xd0,
	0x95, 0x85, 0xf6, 0x0e, 0xda, 0x45, 0x86, 0x15, 0xf7, 0xbd, 0x75, 0xbb, 0x56, 0xce, 0xda, 0xd9,
	0xbf, 0xa8, 0x25, 0x8e, 0xd2, 0xb3, 0x6b, 0xf9, 0x1f, 0xfd, 0xe1, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x7b, 0x8c, 0x5a, 0x81, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NetworkServiceEndpointClient is the client API for NetworkServiceEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkServiceEndpointClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error)
}

type networkServiceEndpointClient struct {
	cc *grpc.ClientConn
}

func NewNetworkServiceEndpointClient(cc *grpc.ClientConn) NetworkServiceEndpointClient {
	return &networkServiceEndpointClient{cc}
}

func (c *networkServiceEndpointClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error) {
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, "/nseconnect.NetworkServiceEndpoint/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceEndpointServer is the server API for NetworkServiceEndpoint service.
type NetworkServiceEndpointServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectReply, error)
}

func RegisterNetworkServiceEndpointServer(s *grpc.Server, srv NetworkServiceEndpointServer) {
	s.RegisterService(&_NetworkServiceEndpoint_serviceDesc, srv)
}

func _NetworkServiceEndpoint_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceEndpointServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nseconnect.NetworkServiceEndpoint/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceEndpointServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkServiceEndpoint_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nseconnect.NetworkServiceEndpoint",
	HandlerType: (*NetworkServiceEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _NetworkServiceEndpoint_Connect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nseconnect.proto",
}

// EndpointOperationsClient is the client API for EndpointOperations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EndpointOperationsClient interface {
	AdvertiseEndpoint(ctx context.Context, in *EndpointAdvertiseRequest, opts ...grpc.CallOption) (*EndpointAdvertiseReply, error)
	RemoveEndpoint(ctx context.Context, in *EndpointRemoveRequest, opts ...grpc.CallOption) (*EndpointRemoveReply, error)
}

type endpointOperationsClient struct {
	cc *grpc.ClientConn
}

func NewEndpointOperationsClient(cc *grpc.ClientConn) EndpointOperationsClient {
	return &endpointOperationsClient{cc}
}

func (c *endpointOperationsClient) AdvertiseEndpoint(ctx context.Context, in *EndpointAdvertiseRequest, opts ...grpc.CallOption) (*EndpointAdvertiseReply, error) {
	out := new(EndpointAdvertiseReply)
	err := c.cc.Invoke(ctx, "/nseconnect.EndpointOperations/AdvertiseEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointOperationsClient) RemoveEndpoint(ctx context.Context, in *EndpointRemoveRequest, opts ...grpc.CallOption) (*EndpointRemoveReply, error) {
	out := new(EndpointRemoveReply)
	err := c.cc.Invoke(ctx, "/nseconnect.EndpointOperations/RemoveEndpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EndpointOperationsServer is the server API for EndpointOperations service.
type EndpointOperationsServer interface {
	AdvertiseEndpoint(context.Context, *EndpointAdvertiseRequest) (*EndpointAdvertiseReply, error)
	RemoveEndpoint(context.Context, *EndpointRemoveRequest) (*EndpointRemoveReply, error)
}

func RegisterEndpointOperationsServer(s *grpc.Server, srv EndpointOperationsServer) {
	s.RegisterService(&_EndpointOperations_serviceDesc, srv)
}

func _EndpointOperations_AdvertiseEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointAdvertiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointOperationsServer).AdvertiseEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nseconnect.EndpointOperations/AdvertiseEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointOperationsServer).AdvertiseEndpoint(ctx, req.(*EndpointAdvertiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EndpointOperations_RemoveEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointOperationsServer).RemoveEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nseconnect.EndpointOperations/RemoveEndpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointOperationsServer).RemoveEndpoint(ctx, req.(*EndpointRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EndpointOperations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nseconnect.EndpointOperations",
	HandlerType: (*EndpointOperationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdvertiseEndpoint",
			Handler:    _EndpointOperations_AdvertiseEndpoint_Handler,
		},
		{
			MethodName: "RemoveEndpoint",
			Handler:    _EndpointOperations_RemoveEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nseconnect.proto",
}
