FROM golang:alpine as build

RUN apk add --update protobuf git bash gcc musl-dev curl

# Compile Delve
RUN echo "Building DLV"
RUN go get github.com/derekparker/delve/cmd/dlv

# Allow delve to run on Alpine based containers.
RUN apk add --no-cache libc6-compat

RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN go get -u golang.org/x/tools/cmd/stringer

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh