// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection_plugin.proto

package plugins

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	connection "github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection"
	connection1 "github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectionValidationStatus int32

const (
	ConnectionValidationStatus_SUCCESS ConnectionValidationStatus = 0
	ConnectionValidationStatus_FAIL    ConnectionValidationStatus = 1
)

var ConnectionValidationStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var ConnectionValidationStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x ConnectionValidationStatus) String() string {
	return proto.EnumName(ConnectionValidationStatus_name, int32(x))
}

func (ConnectionValidationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_27cc99f2c7bc148f, []int{0}
}

type ConnectionWrapper struct {
	// Types that are valid to be assigned to Conn:
	//	*ConnectionWrapper_LocalConnection
	//	*ConnectionWrapper_RemoteConnection
	Conn                 isConnectionWrapper_Conn `protobuf_oneof:"conn"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ConnectionWrapper) Reset()         { *m = ConnectionWrapper{} }
func (m *ConnectionWrapper) String() string { return proto.CompactTextString(m) }
func (*ConnectionWrapper) ProtoMessage()    {}
func (*ConnectionWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_27cc99f2c7bc148f, []int{0}
}

func (m *ConnectionWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionWrapper.Unmarshal(m, b)
}
func (m *ConnectionWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionWrapper.Marshal(b, m, deterministic)
}
func (m *ConnectionWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionWrapper.Merge(m, src)
}
func (m *ConnectionWrapper) XXX_Size() int {
	return xxx_messageInfo_ConnectionWrapper.Size(m)
}
func (m *ConnectionWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionWrapper proto.InternalMessageInfo

type isConnectionWrapper_Conn interface {
	isConnectionWrapper_Conn()
}

type ConnectionWrapper_LocalConnection struct {
	LocalConnection *connection.Connection `protobuf:"bytes,1,opt,name=local_connection,json=localConnection,proto3,oneof"`
}

type ConnectionWrapper_RemoteConnection struct {
	RemoteConnection *connection1.Connection `protobuf:"bytes,2,opt,name=remote_connection,json=remoteConnection,proto3,oneof"`
}

func (*ConnectionWrapper_LocalConnection) isConnectionWrapper_Conn() {}

func (*ConnectionWrapper_RemoteConnection) isConnectionWrapper_Conn() {}

func (m *ConnectionWrapper) GetConn() isConnectionWrapper_Conn {
	if m != nil {
		return m.Conn
	}
	return nil
}

func (m *ConnectionWrapper) GetLocalConnection() *connection.Connection {
	if x, ok := m.GetConn().(*ConnectionWrapper_LocalConnection); ok {
		return x.LocalConnection
	}
	return nil
}

func (m *ConnectionWrapper) GetRemoteConnection() *connection1.Connection {
	if x, ok := m.GetConn().(*ConnectionWrapper_RemoteConnection); ok {
		return x.RemoteConnection
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConnectionWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConnectionWrapper_LocalConnection)(nil),
		(*ConnectionWrapper_RemoteConnection)(nil),
	}
}

type ConnectionValidationResult struct {
	Status               ConnectionValidationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=plugins.ConnectionValidationStatus" json:"status,omitempty"`
	ErrorMessage         string                     `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ConnectionValidationResult) Reset()         { *m = ConnectionValidationResult{} }
func (m *ConnectionValidationResult) String() string { return proto.CompactTextString(m) }
func (*ConnectionValidationResult) ProtoMessage()    {}
func (*ConnectionValidationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_27cc99f2c7bc148f, []int{1}
}

func (m *ConnectionValidationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionValidationResult.Unmarshal(m, b)
}
func (m *ConnectionValidationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionValidationResult.Marshal(b, m, deterministic)
}
func (m *ConnectionValidationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionValidationResult.Merge(m, src)
}
func (m *ConnectionValidationResult) XXX_Size() int {
	return xxx_messageInfo_ConnectionValidationResult.Size(m)
}
func (m *ConnectionValidationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionValidationResult.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionValidationResult proto.InternalMessageInfo

func (m *ConnectionValidationResult) GetStatus() ConnectionValidationStatus {
	if m != nil {
		return m.Status
	}
	return ConnectionValidationStatus_SUCCESS
}

func (m *ConnectionValidationResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("plugins.ConnectionValidationStatus", ConnectionValidationStatus_name, ConnectionValidationStatus_value)
	proto.RegisterType((*ConnectionWrapper)(nil), "plugins.ConnectionWrapper")
	proto.RegisterType((*ConnectionValidationResult)(nil), "plugins.ConnectionValidationResult")
}

func init() { proto.RegisterFile("connection_plugin.proto", fileDescriptor_27cc99f2c7bc148f) }

var fileDescriptor_27cc99f2c7bc148f = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0x5e, 0x65, 0x6c, 0x9a, 0xf9, 0xd1, 0xe5, 0xa2, 0x14, 0x05, 0xd9, 0x2e, 0xe2, 0x21, 0x85,
	0xed, 0xe8, 0x49, 0x87, 0xe2, 0x64, 0x82, 0xb4, 0x4c, 0x8f, 0x23, 0xcb, 0xc2, 0x56, 0x4c, 0x93,
	0x90, 0xa4, 0x7a, 0xf3, 0x57, 0xe9, 0xff, 0x93, 0x25, 0xc5, 0xf4, 0x50, 0x8b, 0xe0, 0x2d, 0x7d,
	0x9e, 0xf7, 0xf9, 0x68, 0xde, 0x80, 0x63, 0x22, 0x38, 0xa7, 0xc4, 0x64, 0x82, 0x2f, 0x24, 0x2b,
	0xd6, 0x19, 0x47, 0x52, 0x09, 0x23, 0x60, 0xd7, 0x7d, 0xe9, 0x88, 0xac, 0x33, 0xb3, 0x29, 0x96,
	0x88, 0x88, 0x3c, 0xe6, 0xd4, 0xbc, 0x0b, 0xf5, 0xaa, 0xa9, 0x7a, 0xcb, 0x08, 0xcd, 0xa9, 0xde,
	0xd4, 0x41, 0x44, 0x70, 0xa3, 0x04, 0x93, 0x0c, 0x73, 0x1a, 0x63, 0x99, 0xc5, 0x4c, 0x10, 0xcc,
	0x62, 0x9f, 0x54, 0x39, 0xba, 0xb4, 0x68, 0xf5, 0xff, 0x10, 0x45, 0x73, 0x61, 0x68, 0x53, 0xca,
	0xe0, 0x33, 0x00, 0xfd, 0xc9, 0x0f, 0xf8, 0xa2, 0xb0, 0x94, 0x54, 0xc1, 0x29, 0x08, 0x6d, 0xc1,
	0x85, 0x9f, 0x3f, 0x09, 0xce, 0x83, 0x8b, 0xde, 0xe8, 0x14, 0x59, 0x02, 0x55, 0x8c, 0xbc, 0xfc,
	0xbe, 0x95, 0x1c, 0x59, 0xda, 0x43, 0x70, 0x06, 0xfa, 0xae, 0x46, 0xd5, 0x6b, 0xc7, 0x7a, 0x9d,
	0x21, 0xc7, 0xfc, 0x6a, 0x16, 0x3a, 0xde, 0x63, 0x37, 0x1d, 0xd0, 0xde, 0x0e, 0x0f, 0x3e, 0x40,
	0xe4, 0xd1, 0x67, 0xcc, 0xb2, 0x15, 0xde, 0x9e, 0x12, 0xaa, 0x0b, 0x66, 0xe0, 0x15, 0xe8, 0x68,
	0x83, 0x4d, 0xa1, 0x6d, 0xe9, 0xc3, 0xd1, 0x10, 0x95, 0x9b, 0x43, 0x75, 0xa2, 0xd4, 0x8e, 0x26,
	0xa5, 0x04, 0x0e, 0xc1, 0x01, 0x55, 0x4a, 0xa8, 0x45, 0x4e, 0xb5, 0xc6, 0x6b, 0x6a, 0xcb, 0xee,
	0x25, 0xfb, 0x16, 0x7c, 0x74, 0xd8, 0xe5, 0xb8, 0x3e, 0xdf, 0x59, 0xc1, 0x1e, 0xe8, 0xa6, 0xf3,
	0xc9, 0xe4, 0x36, 0x4d, 0xc3, 0x16, 0xdc, 0x05, 0xed, 0xbb, 0xeb, 0xe9, 0x2c, 0x0c, 0x46, 0x5f,
	0x01, 0x08, 0xbd, 0xea, 0xc9, 0x56, 0x82, 0x0f, 0x20, 0x9c, 0xcb, 0x15, 0xae, 0xfe, 0x25, 0x8c,
	0x6a, 0xfa, 0x96, 0xab, 0x89, 0x1a, 0x38, 0x38, 0x07, 0xb0, 0xec, 0xf2, 0x57, 0xb7, 0xe6, 0x9b,
	0x71, 0xd7, 0xb9, 0xec, 0xd8, 0xa7, 0x32, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xf0, 0xcb,
	0x0a, 0x19, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionPluginClient is the client API for ConnectionPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionPluginClient interface {
	UpdateConnection(ctx context.Context, in *ConnectionWrapper, opts ...grpc.CallOption) (*ConnectionWrapper, error)
	ValidateConnection(ctx context.Context, in *ConnectionWrapper, opts ...grpc.CallOption) (*ConnectionValidationResult, error)
}

type connectionPluginClient struct {
	cc *grpc.ClientConn
}

func NewConnectionPluginClient(cc *grpc.ClientConn) ConnectionPluginClient {
	return &connectionPluginClient{cc}
}

func (c *connectionPluginClient) UpdateConnection(ctx context.Context, in *ConnectionWrapper, opts ...grpc.CallOption) (*ConnectionWrapper, error) {
	out := new(ConnectionWrapper)
	err := c.cc.Invoke(ctx, "/plugins.ConnectionPlugin/UpdateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionPluginClient) ValidateConnection(ctx context.Context, in *ConnectionWrapper, opts ...grpc.CallOption) (*ConnectionValidationResult, error) {
	out := new(ConnectionValidationResult)
	err := c.cc.Invoke(ctx, "/plugins.ConnectionPlugin/ValidateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectionPluginServer is the server API for ConnectionPlugin service.
type ConnectionPluginServer interface {
	UpdateConnection(context.Context, *ConnectionWrapper) (*ConnectionWrapper, error)
	ValidateConnection(context.Context, *ConnectionWrapper) (*ConnectionValidationResult, error)
}

func RegisterConnectionPluginServer(s *grpc.Server, srv ConnectionPluginServer) {
	s.RegisterService(&_ConnectionPlugin_serviceDesc, srv)
}

func _ConnectionPlugin_UpdateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionPluginServer).UpdateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.ConnectionPlugin/UpdateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionPluginServer).UpdateConnection(ctx, req.(*ConnectionWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionPlugin_ValidateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionWrapper)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionPluginServer).ValidateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.ConnectionPlugin/ValidateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionPluginServer).ValidateConnection(ctx, req.(*ConnectionWrapper))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConnectionPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.ConnectionPlugin",
	HandlerType: (*ConnectionPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConnection",
			Handler:    _ConnectionPlugin_UpdateConnection_Handler,
		},
		{
			MethodName: "ValidateConnection",
			Handler:    _ConnectionPlugin_ValidateConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection_plugin.proto",
}
