// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package plugins

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PluginCapability int32

const (
	PluginCapability_CONNECTION PluginCapability = 0
)

var PluginCapability_name = map[int32]string{
	0: "CONNECTION",
}

var PluginCapability_value = map[string]int32{
	"CONNECTION": 0,
}

func (x PluginCapability) String() string {
	return proto.EnumName(PluginCapability_name, int32(x))
}

func (PluginCapability) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

type PluginInfo struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint             string             `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capabilities         []PluginCapability `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=plugins.PluginCapability" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PluginInfo) Reset()         { *m = PluginInfo{} }
func (m *PluginInfo) String() string { return proto.CompactTextString(m) }
func (*PluginInfo) ProtoMessage()    {}
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *PluginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfo.Unmarshal(m, b)
}
func (m *PluginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfo.Marshal(b, m, deterministic)
}
func (m *PluginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfo.Merge(m, src)
}
func (m *PluginInfo) XXX_Size() int {
	return xxx_messageInfo_PluginInfo.Size(m)
}
func (m *PluginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfo proto.InternalMessageInfo

func (m *PluginInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *PluginInfo) GetCapabilities() []PluginCapability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func init() {
	proto.RegisterEnum("plugins.PluginCapability", PluginCapability_name, PluginCapability_value)
	proto.RegisterType((*PluginInfo)(nil), "plugins.PluginInfo")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x8d, 0x13, 0x9d, 0x1f, 0x52, 0xc7, 0x27, 0x48, 0xed, 0x69, 0xec, 0x54, 0x3c, 0x44,
	0x99, 0x07, 0x4f, 0x9e, 0x4a, 0x0f, 0x03, 0xe9, 0xa4, 0xf8, 0x07, 0x5a, 0xfd, 0x56, 0x02, 0x5d,
	0x12, 0x93, 0x54, 0x08, 0xfe, 0x09, 0x7f, 0xb2, 0x2c, 0x99, 0x82, 0x83, 0x5e, 0xc2, 0x97, 0x97,
	0x87, 0xf7, 0xe5, 0x81, 0xc4, 0x50, 0x27, 0xac, 0x33, 0x9e, 0x6b, 0xa3, 0x9c, 0xc2, 0x33, 0xdd,
	0x0f, 0x9d, 0x90, 0x36, 0x4b, 0xb5, 0xf3, 0x9a, 0xec, 0x1d, 0x6d, 0xb5, 0xf3, 0xf1, 0x8d, 0xc8,
	0xe2, 0x0b, 0xe0, 0x25, 0x40, 0x2b, 0xb9, 0x51, 0x88, 0x70, 0x22, 0x9b, 0x2d, 0xa5, 0x6c, 0xce,
	0xf2, 0xf3, 0x3a, 0xdc, 0x98, 0xc1, 0x94, 0xe4, 0xbb, 0x56, 0x42, 0xba, 0xf4, 0x38, 0xe4, 0x7f,
	0x7f, 0x7c, 0x82, 0x8b, 0xb7, 0x46, 0x37, 0xad, 0xe8, 0x85, 0x13, 0x64, 0xd3, 0xc9, 0x7c, 0x92,
	0x27, 0xcb, 0x1b, 0xbe, 0xdf, 0xe5, 0xb1, 0xba, 0xf8, 0x45, 0x7c, 0xfd, 0x0f, 0xbf, 0x5d, 0xc0,
	0xec, 0x90, 0xc0, 0x04, 0xa0, 0x58, 0x57, 0x55, 0x59, 0xbc, 0xae, 0xd6, 0xd5, 0xec, 0x68, 0xf9,
	0xcd, 0x20, 0x89, 0x50, 0xbd, 0x97, 0xc3, 0x47, 0x98, 0xc6, 0x9b, 0x0c, 0x5e, 0x1d, 0x6c, 0xed,
	0x34, 0xb2, 0x6b, 0xde, 0x29, 0xd5, 0xf5, 0x14, 0x1d, 0xdb, 0x61, 0xc3, 0xcb, 0x9d, 0x32, 0x96,
	0x70, 0x59, 0xd3, 0xc7, 0x40, 0xd6, 0x3d, 0x8b, 0x4f, 0x92, 0x64, 0x2d, 0x8e, 0xa0, 0x63, 0x15,
	0x39, 0xbb, 0x67, 0xed, 0x69, 0xc8, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x07, 0x0f,
	0x69, 0x6f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginRegistryClient is the client API for PluginRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginRegistryClient interface {
	Register(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*empty.Empty, error)
	// RequestLiveness is a stream initiated by NSM to inform the client that NSM is still alive and
	// no re-registration is required. Detection a failure on this "channel" will mean
	// that NSM is gone and the client needs to start re-registration logic.
	RequestLiveness(ctx context.Context, opts ...grpc.CallOption) (PluginRegistry_RequestLivenessClient, error)
}

type pluginRegistryClient struct {
	cc *grpc.ClientConn
}

func NewPluginRegistryClient(cc *grpc.ClientConn) PluginRegistryClient {
	return &pluginRegistryClient{cc}
}

func (c *pluginRegistryClient) Register(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/plugins.PluginRegistry/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryClient) RequestLiveness(ctx context.Context, opts ...grpc.CallOption) (PluginRegistry_RequestLivenessClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PluginRegistry_serviceDesc.Streams[0], "/plugins.PluginRegistry/RequestLiveness", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginRegistryRequestLivenessClient{stream}
	return x, nil
}

type PluginRegistry_RequestLivenessClient interface {
	Send(*empty.Empty) error
	Recv() (*empty.Empty, error)
	grpc.ClientStream
}

type pluginRegistryRequestLivenessClient struct {
	grpc.ClientStream
}

func (x *pluginRegistryRequestLivenessClient) Send(m *empty.Empty) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pluginRegistryRequestLivenessClient) Recv() (*empty.Empty, error) {
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginRegistryServer is the server API for PluginRegistry service.
type PluginRegistryServer interface {
	Register(context.Context, *PluginInfo) (*empty.Empty, error)
	// RequestLiveness is a stream initiated by NSM to inform the client that NSM is still alive and
	// no re-registration is required. Detection a failure on this "channel" will mean
	// that NSM is gone and the client needs to start re-registration logic.
	RequestLiveness(PluginRegistry_RequestLivenessServer) error
}

// UnimplementedPluginRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedPluginRegistryServer struct {
}

func (*UnimplementedPluginRegistryServer) Register(ctx context.Context, req *PluginInfo) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedPluginRegistryServer) RequestLiveness(srv PluginRegistry_RequestLivenessServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestLiveness not implemented")
}

func RegisterPluginRegistryServer(s *grpc.Server, srv PluginRegistryServer) {
	s.RegisterService(&_PluginRegistry_serviceDesc, srv)
}

func _PluginRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.PluginRegistry/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServer).Register(ctx, req.(*PluginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistry_RequestLiveness_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginRegistryServer).RequestLiveness(&pluginRegistryRequestLivenessServer{stream})
}

type PluginRegistry_RequestLivenessServer interface {
	Send(*empty.Empty) error
	Recv() (*empty.Empty, error)
	grpc.ServerStream
}

type pluginRegistryRequestLivenessServer struct {
	grpc.ServerStream
}

func (x *pluginRegistryRequestLivenessServer) Send(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pluginRegistryRequestLivenessServer) Recv() (*empty.Empty, error) {
	m := new(empty.Empty)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PluginRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.PluginRegistry",
	HandlerType: (*PluginRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PluginRegistry_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestLiveness",
			Handler:       _PluginRegistry_RequestLiveness_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "registry.proto",
}
