ARG VPP_AGENT

FROM networkservicemesh/builder:latest as build
RUN CGO_ENABLED=0 GOOS=linux go build  -i -ldflags '-extldflags "-static"' -o /go/bin/vppagent-nsc ./examples/cmd/vppagent-nsc

FROM ${VPP_AGENT} as runtime
COPY --from=build /go/bin/vppagent-nsc /bin/vppagent-nsc
RUN rm /opt/vpp-agent/dev/etcd.conf; echo 'Endpoint: "0.0.0.0:9113"' > /opt/vpp-agent/dev/grpc.conf; echo "disabled: true" > /opt/vpp-agent/dev/linux-plugin.conf
COPY dataplane/vppagent/conf/vpp/startup.conf /etc/vpp/vpp.conf
COPY examples/conf/vppagent-nsc/supervisord.conf /etc/supervisord/supervisord.conf

RUN rm -f /dev/shm/db /dev/shm/global_vm /dev/shm/vpe-api
ENTRYPOINT ["/usr/bin/supervisord","-c","/etc/supervisord/supervisord.conf"]
