FROM networkservicemesh/builder:latest as build

RUN CGO_ENABLED=0 GOOS=linux go build -i -ldflags '-extldflags "-static"' -o /go/bin/admission-webhook ./k8s/cmd/admission-webhook/main.go

FROM alpine as runtime
COPY --from=build /go/bin/admission-webhook /bin/admission-webhook
ENTRYPOINT ["/bin/admission-webhook"]
