FROM gcr.io/spiffe-io/spire-server:0.8.0 as builder

FROM alpine
RUN apk add dumb-init
RUN apk add ca-certificates
RUN mkdir -p /opt/spire/bin
COPY --from=builder /opt/spire/bin/spire-server /opt/spire/bin/spire-server

WORKDIR /opt/spire
ADD ["./pkg/security/scripts/registration.sh", "/opt/spire"]
RUN chmod +x /opt/spire/registration.sh
ENTRYPOINT ["/usr/bin/dumb-init", "/opt/spire/registration.sh"]
