FROM golang:alpine as build
ENV PACKAGEPATH=github.com/ligato/networkservicemesh/
COPY [".","/go/src/${PACKAGEPATH}"]
WORKDIR /go/src/${PACKAGEPATH}/
	RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-extldflags "-static"' -o /go/bin/vppagent-firewall-nse ./examples/cmd/vppagent-firewall-nse
FROM ligato/vpp-agent:v1.7 as runtime
COPY --from=build /go/bin/vppagent-firewall-nse /bin/vppagent-firewall-nse
RUN rm /opt/vpp-agent/dev/etcd.conf /opt/vpp-agent/dev/kafka.conf; echo 'Endpoint: "0.0.0.0:9112"' > /opt/vpp-agent/dev/grpc.conf
COPY dataplane/vppagent/conf/vpp/startup.conf /etc/vpp/vpp.conf
COPY examples/conf/vppagent-firewall-nse/supervisord.conf /etc/supervisord/supervisord.conf