// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectioncontext.proto

package connectioncontext

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Route struct {
	TargetAddr           string   `protobuf:"bytes,1,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectioncontext_c32f57c7cc49c226, []int{0}
}
func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (dst *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(dst, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetTargetAddr() string {
	if m != nil {
		return m.TargetAddr
	}
	return ""
}

type ConnectionContext struct {
	SrcIpAddr            string   `protobuf:"bytes,1,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`
	DstIpAddr            string   `protobuf:"bytes,2,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`
	SrcIpRequired        bool     `protobuf:"varint,3,opt,name=src_ip_required,json=srcIpRequired,proto3" json:"src_ip_required,omitempty"`
	DstIpRequired        bool     `protobuf:"varint,4,opt,name=dst_ip_required,json=dstIpRequired,proto3" json:"dst_ip_required,omitempty"`
	Routes               []*Route `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	ExcludedPrefixes     []string `protobuf:"bytes,6,rep,name=excluded_prefixes,json=excludedPrefixes,proto3" json:"excluded_prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionContext) Reset()         { *m = ConnectionContext{} }
func (m *ConnectionContext) String() string { return proto.CompactTextString(m) }
func (*ConnectionContext) ProtoMessage()    {}
func (*ConnectionContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_connectioncontext_c32f57c7cc49c226, []int{1}
}
func (m *ConnectionContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionContext.Unmarshal(m, b)
}
func (m *ConnectionContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionContext.Marshal(b, m, deterministic)
}
func (dst *ConnectionContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionContext.Merge(dst, src)
}
func (m *ConnectionContext) XXX_Size() int {
	return xxx_messageInfo_ConnectionContext.Size(m)
}
func (m *ConnectionContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionContext.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionContext proto.InternalMessageInfo

func (m *ConnectionContext) GetSrcIpAddr() string {
	if m != nil {
		return m.SrcIpAddr
	}
	return ""
}

func (m *ConnectionContext) GetDstIpAddr() string {
	if m != nil {
		return m.DstIpAddr
	}
	return ""
}

func (m *ConnectionContext) GetSrcIpRequired() bool {
	if m != nil {
		return m.SrcIpRequired
	}
	return false
}

func (m *ConnectionContext) GetDstIpRequired() bool {
	if m != nil {
		return m.DstIpRequired
	}
	return false
}

func (m *ConnectionContext) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *ConnectionContext) GetExcludedPrefixes() []string {
	if m != nil {
		return m.ExcludedPrefixes
	}
	return nil
}

func init() {
	proto.RegisterType((*Route)(nil), "connectioncontext.Route")
	proto.RegisterType((*ConnectionContext)(nil), "connectioncontext.ConnectionContext")
}

func init() {
	proto.RegisterFile("connectioncontext.proto", fileDescriptor_connectioncontext_c32f57c7cc49c226)
}

var fileDescriptor_connectioncontext_c32f57c7cc49c226 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0xc9, 0xc5, 0x0b, 0x66, 0x82, 0x68, 0x62, 0xe1, 0x56, 0x1a, 0xae, 0x90, 0x05, 0xe1,
	0x10, 0xfd, 0x05, 0x7a, 0x95, 0x9d, 0x6c, 0x69, 0x13, 0xce, 0x9d, 0x51, 0x02, 0x92, 0x8d, 0xb3,
	0x13, 0x48, 0xed, 0x2f, 0x97, 0x24, 0xeb, 0x22, 0xa4, 0x9d, 0xef, 0x7d, 0x0f, 0xe6, 0xc1, 0x95,
	0x75, 0x5d, 0x47, 0x56, 0x5a, 0xd7, 0x59, 0xd7, 0x09, 0x8d, 0xb2, 0xef, 0xd9, 0x89, 0xab, 0xca,
	0x15, 0xd8, 0x69, 0xd8, 0x1a, 0x37, 0x08, 0x55, 0x37, 0x50, 0xc8, 0x91, 0x3f, 0x49, 0x9a, 0x23,
	0x22, 0xab, 0xa4, 0x4e, 0x74, 0x6e, 0x60, 0x39, 0x3d, 0x21, 0xf2, 0xee, 0x67, 0x03, 0xe5, 0x21,
	0xfa, 0x87, 0xc5, 0xaf, 0xae, 0xa1, 0xf0, 0x6c, 0x9b, 0xb6, 0xff, 0xaf, 0xe5, 0x9e, 0xed, 0x4b,
	0x3f, 0x59, 0x13, 0x47, 0x2f, 0x91, 0x6f, 0x16, 0x8e, 0x5e, 0x02, 0xbf, 0x85, 0xf3, 0xe0, 0x33,
	0x7d, 0x0f, 0x2d, 0x13, 0xaa, 0xb4, 0x4e, 0xf4, 0xa9, 0x39, 0x9b, 0x3b, 0x4c, 0x38, 0x4e, 0xb9,
	0xd0, 0x13, 0x73, 0x27, 0x4b, 0x6e, 0xee, 0x8a, 0xb9, 0x7b, 0xc8, 0x78, 0xfa, 0xc7, 0xab, 0x6d,
	0x9d, 0xea, 0xe2, 0x41, 0xed, 0xd7, 0x63, 0xcc, 0x0f, 0x9b, 0x90, 0xab, 0xee, 0xa0, 0xa4, 0xd1,
	0x7e, 0x0d, 0x48, 0xd8, 0xf4, 0x4c, 0x1f, 0xed, 0x48, 0x5e, 0x65, 0x75, 0xaa, 0x73, 0x73, 0xf1,
	0x07, 0x5e, 0xc3, 0xfd, 0xf9, 0xf2, 0x6d, 0xbd, 0xe1, 0x7b, 0x36, 0xaf, 0xfb, 0xf8, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0x7b, 0x7b, 0xc1, 0x78, 0x01, 0x00, 0x00,
}
