// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectioncontext.proto

package connectioncontext

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IpFamily_Family int32

const (
	IpFamily_IPV4 IpFamily_Family = 0
	IpFamily_IPV6 IpFamily_Family = 1
)

var IpFamily_Family_name = map[int32]string{
	0: "IPV4",
	1: "IPV6",
}

var IpFamily_Family_value = map[string]int32{
	"IPV4": 0,
	"IPV6": 1,
}

func (x IpFamily_Family) String() string {
	return proto.EnumName(IpFamily_Family_name, int32(x))
}

func (IpFamily_Family) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{2, 0}
}

type IpNeighbor struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	HardwareAddress      string   `protobuf:"bytes,2,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpNeighbor) Reset()         { *m = IpNeighbor{} }
func (m *IpNeighbor) String() string { return proto.CompactTextString(m) }
func (*IpNeighbor) ProtoMessage()    {}
func (*IpNeighbor) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{0}
}

func (m *IpNeighbor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpNeighbor.Unmarshal(m, b)
}
func (m *IpNeighbor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpNeighbor.Marshal(b, m, deterministic)
}
func (m *IpNeighbor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpNeighbor.Merge(m, src)
}
func (m *IpNeighbor) XXX_Size() int {
	return xxx_messageInfo_IpNeighbor.Size(m)
}
func (m *IpNeighbor) XXX_DiscardUnknown() {
	xxx_messageInfo_IpNeighbor.DiscardUnknown(m)
}

var xxx_messageInfo_IpNeighbor proto.InternalMessageInfo

func (m *IpNeighbor) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *IpNeighbor) GetHardwareAddress() string {
	if m != nil {
		return m.HardwareAddress
	}
	return ""
}

type Route struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{1}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type IpFamily struct {
	Family               IpFamily_Family `protobuf:"varint,1,opt,name=family,proto3,enum=connectioncontext.IpFamily_Family" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IpFamily) Reset()         { *m = IpFamily{} }
func (m *IpFamily) String() string { return proto.CompactTextString(m) }
func (*IpFamily) ProtoMessage()    {}
func (*IpFamily) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{2}
}

func (m *IpFamily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpFamily.Unmarshal(m, b)
}
func (m *IpFamily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpFamily.Marshal(b, m, deterministic)
}
func (m *IpFamily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpFamily.Merge(m, src)
}
func (m *IpFamily) XXX_Size() int {
	return xxx_messageInfo_IpFamily.Size(m)
}
func (m *IpFamily) XXX_DiscardUnknown() {
	xxx_messageInfo_IpFamily.DiscardUnknown(m)
}

var xxx_messageInfo_IpFamily proto.InternalMessageInfo

func (m *IpFamily) GetFamily() IpFamily_Family {
	if m != nil {
		return m.Family
	}
	return IpFamily_IPV4
}

type ExtraPrefixRequest struct {
	AddrFamily           *IpFamily `protobuf:"bytes,1,opt,name=addr_family,json=addrFamily,proto3" json:"addr_family,omitempty"`
	PrefixLen            uint32    `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	RequiredNumber       uint32    `protobuf:"varint,3,opt,name=required_number,json=requiredNumber,proto3" json:"required_number,omitempty"`
	RequestedNumber      uint32    `protobuf:"varint,4,opt,name=requested_number,json=requestedNumber,proto3" json:"requested_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExtraPrefixRequest) Reset()         { *m = ExtraPrefixRequest{} }
func (m *ExtraPrefixRequest) String() string { return proto.CompactTextString(m) }
func (*ExtraPrefixRequest) ProtoMessage()    {}
func (*ExtraPrefixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{3}
}

func (m *ExtraPrefixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtraPrefixRequest.Unmarshal(m, b)
}
func (m *ExtraPrefixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtraPrefixRequest.Marshal(b, m, deterministic)
}
func (m *ExtraPrefixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtraPrefixRequest.Merge(m, src)
}
func (m *ExtraPrefixRequest) XXX_Size() int {
	return xxx_messageInfo_ExtraPrefixRequest.Size(m)
}
func (m *ExtraPrefixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtraPrefixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExtraPrefixRequest proto.InternalMessageInfo

func (m *ExtraPrefixRequest) GetAddrFamily() *IpFamily {
	if m != nil {
		return m.AddrFamily
	}
	return nil
}

func (m *ExtraPrefixRequest) GetPrefixLen() uint32 {
	if m != nil {
		return m.PrefixLen
	}
	return 0
}

func (m *ExtraPrefixRequest) GetRequiredNumber() uint32 {
	if m != nil {
		return m.RequiredNumber
	}
	return 0
}

func (m *ExtraPrefixRequest) GetRequestedNumber() uint32 {
	if m != nil {
		return m.RequestedNumber
	}
	return 0
}

type IPContext struct {
	SrcIpAddr            string                `protobuf:"bytes,1,opt,name=src_ip_addr,json=srcIpAddr,proto3" json:"src_ip_addr,omitempty"`
	DstIpAddr            string                `protobuf:"bytes,2,opt,name=dst_ip_addr,json=dstIpAddr,proto3" json:"dst_ip_addr,omitempty"`
	SrcIpRequired        bool                  `protobuf:"varint,3,opt,name=src_ip_required,json=srcIpRequired,proto3" json:"src_ip_required,omitempty"`
	DstIpRequired        bool                  `protobuf:"varint,4,opt,name=dst_ip_required,json=dstIpRequired,proto3" json:"dst_ip_required,omitempty"`
	SrcRoutes            []*Route              `protobuf:"bytes,5,rep,name=src_routes,json=srcRoutes,proto3" json:"src_routes,omitempty"`
	DstRoutes            []*Route              `protobuf:"bytes,6,rep,name=dst_routes,json=dstRoutes,proto3" json:"dst_routes,omitempty"`
	ExcludedPrefixes     []string              `protobuf:"bytes,7,rep,name=excluded_prefixes,json=excludedPrefixes,proto3" json:"excluded_prefixes,omitempty"`
	IpNeighbors          []*IpNeighbor         `protobuf:"bytes,8,rep,name=ip_neighbors,json=ipNeighbors,proto3" json:"ip_neighbors,omitempty"`
	ExtraPrefixRequest   []*ExtraPrefixRequest `protobuf:"bytes,9,rep,name=extra_prefix_request,json=extraPrefixRequest,proto3" json:"extra_prefix_request,omitempty"`
	ExtraPrefixes        []string              `protobuf:"bytes,10,rep,name=extra_prefixes,json=extraPrefixes,proto3" json:"extra_prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IPContext) Reset()         { *m = IPContext{} }
func (m *IPContext) String() string { return proto.CompactTextString(m) }
func (*IPContext) ProtoMessage()    {}
func (*IPContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{4}
}

func (m *IPContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPContext.Unmarshal(m, b)
}
func (m *IPContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPContext.Marshal(b, m, deterministic)
}
func (m *IPContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPContext.Merge(m, src)
}
func (m *IPContext) XXX_Size() int {
	return xxx_messageInfo_IPContext.Size(m)
}
func (m *IPContext) XXX_DiscardUnknown() {
	xxx_messageInfo_IPContext.DiscardUnknown(m)
}

var xxx_messageInfo_IPContext proto.InternalMessageInfo

func (m *IPContext) GetSrcIpAddr() string {
	if m != nil {
		return m.SrcIpAddr
	}
	return ""
}

func (m *IPContext) GetDstIpAddr() string {
	if m != nil {
		return m.DstIpAddr
	}
	return ""
}

func (m *IPContext) GetSrcIpRequired() bool {
	if m != nil {
		return m.SrcIpRequired
	}
	return false
}

func (m *IPContext) GetDstIpRequired() bool {
	if m != nil {
		return m.DstIpRequired
	}
	return false
}

func (m *IPContext) GetSrcRoutes() []*Route {
	if m != nil {
		return m.SrcRoutes
	}
	return nil
}

func (m *IPContext) GetDstRoutes() []*Route {
	if m != nil {
		return m.DstRoutes
	}
	return nil
}

func (m *IPContext) GetExcludedPrefixes() []string {
	if m != nil {
		return m.ExcludedPrefixes
	}
	return nil
}

func (m *IPContext) GetIpNeighbors() []*IpNeighbor {
	if m != nil {
		return m.IpNeighbors
	}
	return nil
}

func (m *IPContext) GetExtraPrefixRequest() []*ExtraPrefixRequest {
	if m != nil {
		return m.ExtraPrefixRequest
	}
	return nil
}

func (m *IPContext) GetExtraPrefixes() []string {
	if m != nil {
		return m.ExtraPrefixes
	}
	return nil
}

type DNSContext struct {
	// ips of DNS Servers for this DNSConfig.  Any given IP may be IPv4 or IPv6
	DnsServerIps []string `protobuf:"bytes,1,rep,name=dns_server_ips,json=dnsServerIps,proto3" json:"dns_server_ips,omitempty"`
	// domains for which this DNSConfig provides resolution.  If empty, all domains.
	ResolvesDomains []string `protobuf:"bytes,2,rep,name=resolves_domains,json=resolvesDomains,proto3" json:"resolves_domains,omitempty"`
	// true if DNSConfig should be used to resolve listed domains listed in
	// resolves_domains over other resolvers that did not request priority.  true is
	// invalid if resolves_domains is empty.
	Prioritize           bool     `protobuf:"varint,3,opt,name=prioritize,proto3" json:"prioritize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSContext) Reset()         { *m = DNSContext{} }
func (m *DNSContext) String() string { return proto.CompactTextString(m) }
func (*DNSContext) ProtoMessage()    {}
func (*DNSContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{5}
}

func (m *DNSContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSContext.Unmarshal(m, b)
}
func (m *DNSContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSContext.Marshal(b, m, deterministic)
}
func (m *DNSContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSContext.Merge(m, src)
}
func (m *DNSContext) XXX_Size() int {
	return xxx_messageInfo_DNSContext.Size(m)
}
func (m *DNSContext) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSContext.DiscardUnknown(m)
}

var xxx_messageInfo_DNSContext proto.InternalMessageInfo

func (m *DNSContext) GetDnsServerIps() []string {
	if m != nil {
		return m.DnsServerIps
	}
	return nil
}

func (m *DNSContext) GetResolvesDomains() []string {
	if m != nil {
		return m.ResolvesDomains
	}
	return nil
}

func (m *DNSContext) GetPrioritize() bool {
	if m != nil {
		return m.Prioritize
	}
	return false
}

type ConnectionContext struct {
	IpContext            *IPContext  `protobuf:"bytes,1,opt,name=ip_context,json=ipContext,proto3" json:"ip_context,omitempty"`
	DnsContext           *DNSContext `protobuf:"bytes,2,opt,name=dns_context,json=dnsContext,proto3" json:"dns_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectionContext) Reset()         { *m = ConnectionContext{} }
func (m *ConnectionContext) String() string { return proto.CompactTextString(m) }
func (*ConnectionContext) ProtoMessage()    {}
func (*ConnectionContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_c30b3f1555e8b686, []int{6}
}

func (m *ConnectionContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionContext.Unmarshal(m, b)
}
func (m *ConnectionContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionContext.Marshal(b, m, deterministic)
}
func (m *ConnectionContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionContext.Merge(m, src)
}
func (m *ConnectionContext) XXX_Size() int {
	return xxx_messageInfo_ConnectionContext.Size(m)
}
func (m *ConnectionContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionContext.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionContext proto.InternalMessageInfo

func (m *ConnectionContext) GetIpContext() *IPContext {
	if m != nil {
		return m.IpContext
	}
	return nil
}

func (m *ConnectionContext) GetDnsContext() *DNSContext {
	if m != nil {
		return m.DnsContext
	}
	return nil
}

func init() {
	proto.RegisterEnum("connectioncontext.IpFamily_Family", IpFamily_Family_name, IpFamily_Family_value)
	proto.RegisterType((*IpNeighbor)(nil), "connectioncontext.IpNeighbor")
	proto.RegisterType((*Route)(nil), "connectioncontext.Route")
	proto.RegisterType((*IpFamily)(nil), "connectioncontext.IpFamily")
	proto.RegisterType((*ExtraPrefixRequest)(nil), "connectioncontext.ExtraPrefixRequest")
	proto.RegisterType((*IPContext)(nil), "connectioncontext.IPContext")
	proto.RegisterType((*DNSContext)(nil), "connectioncontext.DNSContext")
	proto.RegisterType((*ConnectionContext)(nil), "connectioncontext.ConnectionContext")
}

func init() { proto.RegisterFile("connectioncontext.proto", fileDescriptor_c30b3f1555e8b686) }

var fileDescriptor_c30b3f1555e8b686 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x36, 0x49, 0x1b, 0xb3, 0x27, 0x6d, 0x92, 0x8e, 0xa2, 0x0b, 0xb6, 0xb5, 0x2c, 0x56, 0x2b,
	0x42, 0x2f, 0xaa, 0x28, 0xa8, 0x88, 0xda, 0xaa, 0x04, 0xa4, 0x84, 0x29, 0x28, 0x78, 0x33, 0x6c,
	0x77, 0x4e, 0xed, 0x40, 0x32, 0x3b, 0x9d, 0xd9, 0xd4, 0x28, 0xf8, 0x0e, 0xbe, 0x94, 0x6f, 0xe5,
	0x85, 0xcc, 0xdf, 0x36, 0x90, 0xa0, 0x57, 0x39, 0xf9, 0xce, 0x77, 0xfe, 0xbf, 0x1d, 0xb8, 0x5d,
	0x94, 0x52, 0x62, 0x51, 0x89, 0x52, 0x16, 0xa5, 0xac, 0x70, 0x56, 0xed, 0x2b, 0x5d, 0x56, 0x25,
	0xd9, 0x58, 0x70, 0x64, 0x1f, 0x00, 0x86, 0xea, 0x18, 0xc5, 0xd7, 0xf3, 0xd3, 0x52, 0x93, 0x1e,
	0x34, 0x85, 0x4a, 0x1b, 0x3b, 0x8d, 0xbd, 0x84, 0x36, 0x85, 0x22, 0x0f, 0x61, 0x70, 0x9e, 0x6b,
	0xfe, 0x2d, 0xd7, 0xc8, 0x72, 0xce, 0x35, 0x1a, 0x93, 0x36, 0x9d, 0xb7, 0x1f, 0xf1, 0x37, 0x1e,
	0xce, 0xee, 0xc2, 0x2a, 0x2d, 0xa7, 0x15, 0x92, 0x5b, 0xd0, 0x56, 0x1a, 0xcf, 0xc4, 0x2c, 0xe4,
	0x09, 0xff, 0x32, 0x0e, 0x9d, 0xa1, 0x7a, 0x9f, 0x4f, 0xc4, 0xf8, 0x3b, 0x79, 0x0e, 0xed, 0x33,
	0x67, 0x39, 0x4e, 0xef, 0x20, 0xdb, 0x5f, 0x6c, 0x39, 0x92, 0xf7, 0xfd, 0x0f, 0x0d, 0x11, 0xd9,
	0x26, 0xb4, 0x43, 0x96, 0x0e, 0xac, 0x0c, 0x47, 0x9f, 0x9e, 0x0c, 0xae, 0x05, 0xeb, 0xe9, 0xa0,
	0x91, 0xfd, 0x6e, 0x00, 0x79, 0x37, 0xab, 0x74, 0x3e, 0x72, 0x55, 0x29, 0x5e, 0x4c, 0xd1, 0x54,
	0xe4, 0x25, 0x74, 0x6d, 0xff, 0x6c, 0xae, 0x6a, 0xf7, 0xe0, 0xce, 0x3f, 0xaa, 0x52, 0xb0, 0xfc,
	0x50, 0x68, 0x0b, 0xc0, 0x0f, 0xc1, 0xc6, 0x28, 0xdd, 0x02, 0xd6, 0x69, 0xe2, 0x91, 0x8f, 0x28,
	0xc9, 0x03, 0xe8, 0x6b, 0xbc, 0x98, 0x0a, 0x8d, 0x9c, 0xc9, 0xe9, 0xe4, 0x14, 0x75, 0xda, 0x72,
	0x9c, 0x5e, 0x84, 0x8f, 0x1d, 0x6a, 0xd7, 0xa9, 0x7d, 0x43, 0x57, 0xcc, 0x15, 0xc7, 0xec, 0xd7,
	0xb8, 0xa7, 0x66, 0x7f, 0x5a, 0x90, 0x0c, 0x47, 0x87, 0xbe, 0x2b, 0xb2, 0x0d, 0x5d, 0xa3, 0x0b,
	0x26, 0x94, 0xbb, 0x42, 0x58, 0x6c, 0x62, 0x74, 0x31, 0x54, 0x76, 0xff, 0xd6, 0xcf, 0x4d, 0x55,
	0xfb, 0xfd, 0x89, 0x12, 0x6e, 0xaa, 0xe0, 0xbf, 0x0f, 0xfd, 0x10, 0x1f, 0x3b, 0x72, 0x1d, 0x76,
	0xe8, 0xba, 0xcb, 0x41, 0x03, 0x68, 0x79, 0x21, 0x4f, 0xcd, 0x5b, 0xf1, 0x3c, 0x97, 0xab, 0xe6,
	0x3d, 0x03, 0xb0, 0xf9, 0xb4, 0x3d, 0xb8, 0x49, 0x57, 0x77, 0x5a, 0x7b, 0xdd, 0x83, 0x74, 0xc9,
	0x36, 0x9d, 0x22, 0x5c, 0xa3, 0xce, 0x32, 0x36, 0xd0, 0x16, 0x08, 0x81, 0xed, 0xff, 0x05, 0x72,
	0x53, 0x85, 0xc0, 0x47, 0xb0, 0x81, 0xb3, 0x62, 0x3c, 0xe5, 0xc8, 0x99, 0xdf, 0x3c, 0x9a, 0xf4,
	0xfa, 0x4e, 0x6b, 0x2f, 0xa1, 0x83, 0xe8, 0x18, 0x05, 0x9c, 0xbc, 0x86, 0x35, 0xa1, 0x98, 0x0c,
	0xaa, 0x36, 0x69, 0xc7, 0xd5, 0xd9, 0x5a, 0x7a, 0xee, 0xa8, 0x7d, 0xda, 0x15, 0xb5, 0x6d, 0xc8,
	0x67, 0xb8, 0x89, 0x56, 0x45, 0xa1, 0x16, 0x0b, 0xe7, 0x49, 0x13, 0x97, 0x69, 0x77, 0x49, 0xa6,
	0x45, 0xd1, 0x51, 0x82, 0x8b, 0x42, 0xdc, 0x85, 0xde, 0x7c, 0x62, 0x34, 0x29, 0xb8, 0x21, 0xd6,
	0xe7, 0xb8, 0x68, 0xb2, 0x9f, 0x00, 0x47, 0xc7, 0x27, 0xf1, 0xfc, 0xf7, 0xa0, 0xc7, 0xa5, 0x61,
	0x06, 0xf5, 0x25, 0x6a, 0x26, 0x94, 0x49, 0x1b, 0x2e, 0x68, 0x8d, 0x4b, 0x73, 0xe2, 0xc0, 0xa1,
	0x32, 0x5e, 0x5d, 0xa6, 0x1c, 0x5f, 0xa2, 0x61, 0xbc, 0x9c, 0xe4, 0x42, 0xda, 0x8f, 0xd5, 0xf2,
	0xfa, 0x11, 0x3f, 0xf2, 0x30, 0xd9, 0xb6, 0x82, 0x16, 0xa5, 0x16, 0x95, 0xf8, 0x81, 0x41, 0x0a,
	0x73, 0x48, 0xf6, 0xab, 0x01, 0x1b, 0x87, 0xf5, 0x88, 0xb1, 0x8d, 0x17, 0x00, 0x42, 0xb1, 0x30,
	0x70, 0xf8, 0x86, 0x36, 0x97, 0x2d, 0x35, 0xea, 0x96, 0x26, 0x42, 0xc5, 0xe0, 0x57, 0xd0, 0xb5,
	0x33, 0xc4, 0xe8, 0xa6, 0x8b, 0x5e, 0x76, 0x92, 0xab, 0xb9, 0x29, 0x70, 0x69, 0x82, 0xfd, 0xf6,
	0xc6, 0x97, 0xc5, 0xd7, 0xeb, 0xb4, 0xed, 0xde, 0xb5, 0xc7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x6e, 0xf0, 0x60, 0xf2, 0x04, 0x00, 0x00,
}
