// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crossconnect.proto

package crossconnect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import connection "github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/local/connection"
import connection1 "github.com/networkservicemesh/networkservicemesh/controlplane/pkg/apis/remote/connection"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CrossConnectEventType int32

const (
	CrossConnectEventType_INITIAL_STATE_TRANSFER CrossConnectEventType = 0
	CrossConnectEventType_UPDATE                 CrossConnectEventType = 1
	CrossConnectEventType_DELETE                 CrossConnectEventType = 2
)

var CrossConnectEventType_name = map[int32]string{
	0: "INITIAL_STATE_TRANSFER",
	1: "UPDATE",
	2: "DELETE",
}
var CrossConnectEventType_value = map[string]int32{
	"INITIAL_STATE_TRANSFER": 0,
	"UPDATE":                 1,
	"DELETE":                 2,
}

func (x CrossConnectEventType) String() string {
	return proto.EnumName(CrossConnectEventType_name, int32(x))
}
func (CrossConnectEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_crossconnect_46dd6bbc027b8f27, []int{0}
}

type CrossConnectEvent struct {
	Type                 CrossConnectEventType    `protobuf:"varint,1,opt,name=type,proto3,enum=crossconnect.CrossConnectEventType" json:"type,omitempty"`
	CrossConnects        map[string]*CrossConnect `protobuf:"bytes,2,rep,name=cross_connects,json=crossConnects,proto3" json:"cross_connects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CrossConnectEvent) Reset()         { *m = CrossConnectEvent{} }
func (m *CrossConnectEvent) String() string { return proto.CompactTextString(m) }
func (*CrossConnectEvent) ProtoMessage()    {}
func (*CrossConnectEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_crossconnect_46dd6bbc027b8f27, []int{0}
}
func (m *CrossConnectEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossConnectEvent.Unmarshal(m, b)
}
func (m *CrossConnectEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossConnectEvent.Marshal(b, m, deterministic)
}
func (dst *CrossConnectEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossConnectEvent.Merge(dst, src)
}
func (m *CrossConnectEvent) XXX_Size() int {
	return xxx_messageInfo_CrossConnectEvent.Size(m)
}
func (m *CrossConnectEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossConnectEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CrossConnectEvent proto.InternalMessageInfo

func (m *CrossConnectEvent) GetType() CrossConnectEventType {
	if m != nil {
		return m.Type
	}
	return CrossConnectEventType_INITIAL_STATE_TRANSFER
}

func (m *CrossConnectEvent) GetCrossConnects() map[string]*CrossConnect {
	if m != nil {
		return m.CrossConnects
	}
	return nil
}

type CrossConnect struct {
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Types that are valid to be assigned to Source:
	//	*CrossConnect_LocalSource
	//	*CrossConnect_RemoteSource
	Source isCrossConnect_Source `protobuf_oneof:"source"`
	// Types that are valid to be assigned to Destination:
	//	*CrossConnect_LocalDestination
	//	*CrossConnect_RemoteDestination
	Destination          isCrossConnect_Destination `protobuf_oneof:"destination"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CrossConnect) Reset()         { *m = CrossConnect{} }
func (m *CrossConnect) String() string { return proto.CompactTextString(m) }
func (*CrossConnect) ProtoMessage()    {}
func (*CrossConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_crossconnect_46dd6bbc027b8f27, []int{1}
}
func (m *CrossConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossConnect.Unmarshal(m, b)
}
func (m *CrossConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossConnect.Marshal(b, m, deterministic)
}
func (dst *CrossConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossConnect.Merge(dst, src)
}
func (m *CrossConnect) XXX_Size() int {
	return xxx_messageInfo_CrossConnect.Size(m)
}
func (m *CrossConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossConnect.DiscardUnknown(m)
}

var xxx_messageInfo_CrossConnect proto.InternalMessageInfo

func (m *CrossConnect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CrossConnect) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type isCrossConnect_Source interface {
	isCrossConnect_Source()
}

type CrossConnect_LocalSource struct {
	LocalSource *connection.Connection `protobuf:"bytes,4,opt,name=local_source,json=localSource,proto3,oneof"`
}

type CrossConnect_RemoteSource struct {
	RemoteSource *connection1.Connection `protobuf:"bytes,5,opt,name=remote_source,json=remoteSource,proto3,oneof"`
}

func (*CrossConnect_LocalSource) isCrossConnect_Source() {}

func (*CrossConnect_RemoteSource) isCrossConnect_Source() {}

func (m *CrossConnect) GetSource() isCrossConnect_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *CrossConnect) GetLocalSource() *connection.Connection {
	if x, ok := m.GetSource().(*CrossConnect_LocalSource); ok {
		return x.LocalSource
	}
	return nil
}

func (m *CrossConnect) GetRemoteSource() *connection1.Connection {
	if x, ok := m.GetSource().(*CrossConnect_RemoteSource); ok {
		return x.RemoteSource
	}
	return nil
}

type isCrossConnect_Destination interface {
	isCrossConnect_Destination()
}

type CrossConnect_LocalDestination struct {
	LocalDestination *connection.Connection `protobuf:"bytes,6,opt,name=local_destination,json=localDestination,proto3,oneof"`
}

type CrossConnect_RemoteDestination struct {
	RemoteDestination *connection1.Connection `protobuf:"bytes,7,opt,name=remote_destination,json=remoteDestination,proto3,oneof"`
}

func (*CrossConnect_LocalDestination) isCrossConnect_Destination() {}

func (*CrossConnect_RemoteDestination) isCrossConnect_Destination() {}

func (m *CrossConnect) GetDestination() isCrossConnect_Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *CrossConnect) GetLocalDestination() *connection.Connection {
	if x, ok := m.GetDestination().(*CrossConnect_LocalDestination); ok {
		return x.LocalDestination
	}
	return nil
}

func (m *CrossConnect) GetRemoteDestination() *connection1.Connection {
	if x, ok := m.GetDestination().(*CrossConnect_RemoteDestination); ok {
		return x.RemoteDestination
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CrossConnect) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CrossConnect_OneofMarshaler, _CrossConnect_OneofUnmarshaler, _CrossConnect_OneofSizer, []interface{}{
		(*CrossConnect_LocalSource)(nil),
		(*CrossConnect_RemoteSource)(nil),
		(*CrossConnect_LocalDestination)(nil),
		(*CrossConnect_RemoteDestination)(nil),
	}
}

func _CrossConnect_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CrossConnect)
	// source
	switch x := m.Source.(type) {
	case *CrossConnect_LocalSource:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LocalSource); err != nil {
			return err
		}
	case *CrossConnect_RemoteSource:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoteSource); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CrossConnect.Source has unexpected type %T", x)
	}
	// destination
	switch x := m.Destination.(type) {
	case *CrossConnect_LocalDestination:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LocalDestination); err != nil {
			return err
		}
	case *CrossConnect_RemoteDestination:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RemoteDestination); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CrossConnect.Destination has unexpected type %T", x)
	}
	return nil
}

func _CrossConnect_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CrossConnect)
	switch tag {
	case 4: // source.local_source
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(connection.Connection)
		err := b.DecodeMessage(msg)
		m.Source = &CrossConnect_LocalSource{msg}
		return true, err
	case 5: // source.remote_source
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(connection1.Connection)
		err := b.DecodeMessage(msg)
		m.Source = &CrossConnect_RemoteSource{msg}
		return true, err
	case 6: // destination.local_destination
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(connection.Connection)
		err := b.DecodeMessage(msg)
		m.Destination = &CrossConnect_LocalDestination{msg}
		return true, err
	case 7: // destination.remote_destination
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(connection1.Connection)
		err := b.DecodeMessage(msg)
		m.Destination = &CrossConnect_RemoteDestination{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CrossConnect_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CrossConnect)
	// source
	switch x := m.Source.(type) {
	case *CrossConnect_LocalSource:
		s := proto.Size(x.LocalSource)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CrossConnect_RemoteSource:
		s := proto.Size(x.RemoteSource)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// destination
	switch x := m.Destination.(type) {
	case *CrossConnect_LocalDestination:
		s := proto.Size(x.LocalDestination)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CrossConnect_RemoteDestination:
		s := proto.Size(x.RemoteDestination)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*CrossConnectEvent)(nil), "crossconnect.CrossConnectEvent")
	proto.RegisterMapType((map[string]*CrossConnect)(nil), "crossconnect.CrossConnectEvent.CrossConnectsEntry")
	proto.RegisterType((*CrossConnect)(nil), "crossconnect.CrossConnect")
	proto.RegisterEnum("crossconnect.CrossConnectEventType", CrossConnectEventType_name, CrossConnectEventType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorCrossConnectClient is the client API for MonitorCrossConnect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorCrossConnectClient interface {
	MonitorCrossConnects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorCrossConnect_MonitorCrossConnectsClient, error)
}

type monitorCrossConnectClient struct {
	cc *grpc.ClientConn
}

func NewMonitorCrossConnectClient(cc *grpc.ClientConn) MonitorCrossConnectClient {
	return &monitorCrossConnectClient{cc}
}

func (c *monitorCrossConnectClient) MonitorCrossConnects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MonitorCrossConnect_MonitorCrossConnectsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MonitorCrossConnect_serviceDesc.Streams[0], "/crossconnect.MonitorCrossConnect/MonitorCrossConnects", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorCrossConnectMonitorCrossConnectsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MonitorCrossConnect_MonitorCrossConnectsClient interface {
	Recv() (*CrossConnectEvent, error)
	grpc.ClientStream
}

type monitorCrossConnectMonitorCrossConnectsClient struct {
	grpc.ClientStream
}

func (x *monitorCrossConnectMonitorCrossConnectsClient) Recv() (*CrossConnectEvent, error) {
	m := new(CrossConnectEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorCrossConnectServer is the server API for MonitorCrossConnect service.
type MonitorCrossConnectServer interface {
	MonitorCrossConnects(*empty.Empty, MonitorCrossConnect_MonitorCrossConnectsServer) error
}

func RegisterMonitorCrossConnectServer(s *grpc.Server, srv MonitorCrossConnectServer) {
	s.RegisterService(&_MonitorCrossConnect_serviceDesc, srv)
}

func _MonitorCrossConnect_MonitorCrossConnects_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitorCrossConnectServer).MonitorCrossConnects(m, &monitorCrossConnectMonitorCrossConnectsServer{stream})
}

type MonitorCrossConnect_MonitorCrossConnectsServer interface {
	Send(*CrossConnectEvent) error
	grpc.ServerStream
}

type monitorCrossConnectMonitorCrossConnectsServer struct {
	grpc.ServerStream
}

func (x *monitorCrossConnectMonitorCrossConnectsServer) Send(m *CrossConnectEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _MonitorCrossConnect_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crossconnect.MonitorCrossConnect",
	HandlerType: (*MonitorCrossConnectServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorCrossConnects",
			Handler:       _MonitorCrossConnect_MonitorCrossConnects_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crossconnect.proto",
}

func init() { proto.RegisterFile("crossconnect.proto", fileDescriptor_crossconnect_46dd6bbc027b8f27) }

var fileDescriptor_crossconnect_46dd6bbc027b8f27 = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x97, 0x6c, 0xeb, 0xd8, 0xeb, 0x0f, 0xb5, 0x06, 0xa6, 0x28, 0x02, 0x51, 0x8d, 0x4b,
	0xc5, 0xc1, 0xd9, 0xba, 0x03, 0x68, 0x27, 0xba, 0x36, 0x88, 0x6a, 0xa3, 0x02, 0x37, 0x1c, 0x90,
	0x90, 0xaa, 0x34, 0x35, 0x69, 0xd4, 0xd4, 0x8e, 0x62, 0xb7, 0x28, 0x7f, 0x00, 0x7f, 0x33, 0x57,
	0x14, 0x3b, 0x85, 0x54, 0xeb, 0xd8, 0x0e, 0xbb, 0x54, 0xaf, 0xdf, 0xf7, 0xde, 0xe7, 0xfb, 0x62,
	0x3f, 0x03, 0x0a, 0x52, 0x2e, 0x44, 0xc0, 0x19, 0xa3, 0x81, 0xc4, 0x49, 0xca, 0x25, 0x47, 0xb5,
	0xb2, 0x66, 0xcf, 0xc3, 0x48, 0xce, 0x57, 0x53, 0x1c, 0xf0, 0xa5, 0xc3, 0xa8, 0xfc, 0xc9, 0xd3,
	0x85, 0xa0, 0xe9, 0x3a, 0x0a, 0xe8, 0x92, 0x8a, 0xf9, 0x2e, 0x29, 0xe0, 0x4c, 0xa6, 0x3c, 0x4e,
	0x62, 0x9f, 0x51, 0x27, 0x59, 0x84, 0x8e, 0x9f, 0x44, 0xc2, 0x89, 0x79, 0xe0, 0xc7, 0x4e, 0x41,
	0x8d, 0x38, 0x2b, 0x85, 0xda, 0xd7, 0x8e, 0x1e, 0xc9, 0x29, 0xa5, 0x4b, 0x2e, 0xe9, 0x7f, 0xad,
	0x2e, 0x4b, 0x56, 0x21, 0x8f, 0x7d, 0x16, 0x3a, 0x2a, 0x31, 0x5d, 0xfd, 0x78, 0xbf, 0x3e, 0xc7,
	0x17, 0xf8, 0xdc, 0x49, 0x64, 0x96, 0x50, 0xe1, 0xd0, 0x65, 0x22, 0x33, 0xfd, 0xab, 0x7b, 0x4f,
	0x7f, 0x99, 0xd0, 0xea, 0xe7, 0x27, 0xd4, 0xd7, 0x54, 0x77, 0x4d, 0x99, 0x44, 0x6f, 0xe1, 0x20,
	0x6f, 0xb0, 0x8c, 0xb6, 0xd1, 0x69, 0x74, 0x5f, 0xe3, 0xad, 0x73, 0xbd, 0x55, 0xee, 0x65, 0x09,
	0x25, 0xaa, 0x01, 0x7d, 0x83, 0x86, 0xaa, 0x9d, 0x14, 0xc5, 0xc2, 0x32, 0xdb, 0xfb, 0x9d, 0x6a,
	0xb7, 0x7b, 0x0f, 0x62, 0x4b, 0x11, 0x2e, 0x93, 0x69, 0x46, 0xea, 0x41, 0x59, 0xb3, 0xbf, 0x03,
	0xba, 0x5d, 0x84, 0x9a, 0xb0, 0xbf, 0xa0, 0x99, 0x1a, 0xf4, 0x98, 0xe4, 0x21, 0x3a, 0x83, 0xc3,
	0xb5, 0x1f, 0xaf, 0xa8, 0x65, 0xb6, 0x8d, 0x4e, 0xb5, 0x6b, 0xdf, 0xed, 0x4c, 0x74, 0xe1, 0xa5,
	0xf9, 0xce, 0x38, 0xfd, 0x6d, 0x42, 0xad, 0x9c, 0x43, 0x0d, 0x30, 0xa3, 0x59, 0xc1, 0x35, 0xa3,
	0x19, 0xb2, 0xe0, 0x28, 0xf1, 0xb3, 0x98, 0xfb, 0x33, 0x05, 0x3e, 0x26, 0x9b, 0xbf, 0xa8, 0x07,
	0x35, 0xb5, 0x0e, 0x13, 0xc1, 0x57, 0x69, 0x40, 0xad, 0x03, 0xe5, 0xfb, 0x02, 0x2b, 0x11, 0x97,
	0x6e, 0xab, 0xff, 0x37, 0xfc, 0xb8, 0x47, 0xaa, 0x2a, 0x3d, 0x56, 0x2d, 0x68, 0x00, 0x75, 0x7d,
	0xcf, 0x1b, 0xc6, 0xa1, 0x62, 0xbc, 0xc4, 0x5a, 0xbd, 0x13, 0x52, 0xd3, 0xf9, 0x82, 0x72, 0x0d,
	0x2d, 0x3d, 0xc8, 0x8c, 0x0a, 0x19, 0x31, 0x3f, 0x2f, 0xb2, 0x2a, 0x0f, 0x98, 0xc6, 0x20, 0x4d,
	0x95, 0x1e, 0xfc, 0xeb, 0x43, 0x23, 0x40, 0xc5, 0x48, 0x65, 0xda, 0xd1, 0x43, 0xe6, 0x32, 0x48,
	0x4b, 0xe7, 0x4b, 0xbc, 0xab, 0x27, 0x50, 0xd1, 0xdf, 0x76, 0x55, 0x87, 0x6a, 0x09, 0xf9, 0xe6,
	0x1a, 0x9e, 0xef, 0xdc, 0x28, 0x64, 0xc3, 0xc9, 0x70, 0x34, 0xf4, 0x86, 0xbd, 0x9b, 0xc9, 0xd8,
	0xeb, 0x79, 0xee, 0xc4, 0x23, 0xbd, 0xd1, 0xf8, 0x83, 0x4b, 0x9a, 0x7b, 0x08, 0xa0, 0xf2, 0xf5,
	0xf3, 0xa0, 0xe7, 0xb9, 0x4d, 0x23, 0x8f, 0x07, 0xee, 0x8d, 0xeb, 0xb9, 0x4d, 0xb3, 0x3b, 0x87,
	0xa7, 0x9f, 0x38, 0x8b, 0x24, 0x4f, 0xb7, 0x2e, 0xf3, 0x0b, 0x3c, 0xdb, 0x21, 0x0b, 0x74, 0x82,
	0x43, 0xce, 0xc3, 0x98, 0xe2, 0xcd, 0x7b, 0xc1, 0x6e, 0xfe, 0x36, 0xec, 0x57, 0xf7, 0xac, 0xeb,
	0x99, 0x31, 0xad, 0xa8, 0x96, 0x8b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xaf, 0xed, 0x98,
	0x74, 0x04, 0x00, 0x00,
}
