// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nsmconnect.proto

package nsmconnect

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/ligato/networkservicemesh/pkg/nsm/apis/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ConnectionRequest is sent by a NSM client to build a connection.
type ConnectionRequest struct {
	// Since connection request will trigger certain actions
	// executed by NSM for a client to address idempotency, request_id
	// will be tracked.
	RequestId            string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	NetworkServiceName   string                   `protobuf:"bytes,2,opt,name=network_service_name,json=networkServiceName" json:"network_service_name,omitempty"`
	LinuxNamespace       string                   `protobuf:"bytes,3,opt,name=linux_namespace,json=linuxNamespace" json:"linux_namespace,omitempty"`
	Interface            []*common.LocalMechanism `protobuf:"bytes,4,rep,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmconnect_e1d5841ad497266e, []int{0}
}
func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (dst *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(dst, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ConnectionRequest) GetNetworkServiceName() string {
	if m != nil {
		return m.NetworkServiceName
	}
	return ""
}

func (m *ConnectionRequest) GetLinuxNamespace() string {
	if m != nil {
		return m.LinuxNamespace
	}
	return ""
}

func (m *ConnectionRequest) GetInterface() []*common.LocalMechanism {
	if m != nil {
		return m.Interface
	}
	return nil
}

type ConnectionParameters struct {
	ConnectionParameters map[string]string `protobuf:"bytes,1,rep,name=connection_parameters,json=connectionParameters" json:"connection_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConnectionParameters) Reset()         { *m = ConnectionParameters{} }
func (m *ConnectionParameters) String() string { return proto.CompactTextString(m) }
func (*ConnectionParameters) ProtoMessage()    {}
func (*ConnectionParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmconnect_e1d5841ad497266e, []int{1}
}
func (m *ConnectionParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionParameters.Unmarshal(m, b)
}
func (m *ConnectionParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionParameters.Marshal(b, m, deterministic)
}
func (dst *ConnectionParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionParameters.Merge(dst, src)
}
func (m *ConnectionParameters) XXX_Size() int {
	return xxx_messageInfo_ConnectionParameters.Size(m)
}
func (m *ConnectionParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionParameters proto.InternalMessageInfo

func (m *ConnectionParameters) GetConnectionParameters() map[string]string {
	if m != nil {
		return m.ConnectionParameters
	}
	return nil
}

// ConnectionReply is sent back by NSM as a reply to ConnectionRequest
// accepted true will indicate that the connection is accepted, otherwise false
// indicates that connection was refused and admission_error will provide details
// why connection was refused.
type ConnectionReply struct {
	Accepted             bool                   `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
	AdmissionError       string                 `protobuf:"bytes,2,opt,name=admission_error,json=admissionError" json:"admission_error,omitempty"`
	ConnectionParameters *ConnectionParameters  `protobuf:"bytes,3,opt,name=connection_parameters,json=connectionParameters" json:"connection_parameters,omitempty"`
	Interface            *common.LocalMechanism `protobuf:"bytes,4,opt,name=interface" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConnectionReply) Reset()         { *m = ConnectionReply{} }
func (m *ConnectionReply) String() string { return proto.CompactTextString(m) }
func (*ConnectionReply) ProtoMessage()    {}
func (*ConnectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_nsmconnect_e1d5841ad497266e, []int{2}
}
func (m *ConnectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionReply.Unmarshal(m, b)
}
func (m *ConnectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionReply.Marshal(b, m, deterministic)
}
func (dst *ConnectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionReply.Merge(dst, src)
}
func (m *ConnectionReply) XXX_Size() int {
	return xxx_messageInfo_ConnectionReply.Size(m)
}
func (m *ConnectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionReply proto.InternalMessageInfo

func (m *ConnectionReply) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func (m *ConnectionReply) GetAdmissionError() string {
	if m != nil {
		return m.AdmissionError
	}
	return ""
}

func (m *ConnectionReply) GetConnectionParameters() *ConnectionParameters {
	if m != nil {
		return m.ConnectionParameters
	}
	return nil
}

func (m *ConnectionReply) GetInterface() *common.LocalMechanism {
	if m != nil {
		return m.Interface
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectionRequest)(nil), "nsmconnect.ConnectionRequest")
	proto.RegisterType((*ConnectionParameters)(nil), "nsmconnect.ConnectionParameters")
	proto.RegisterMapType((map[string]string)(nil), "nsmconnect.ConnectionParameters.ConnectionParametersEntry")
	proto.RegisterType((*ConnectionReply)(nil), "nsmconnect.ConnectionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientConnectionClient is the client API for ClientConnection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientConnectionClient interface {
	RequestConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionReply, error)
}

type clientConnectionClient struct {
	cc *grpc.ClientConn
}

func NewClientConnectionClient(cc *grpc.ClientConn) ClientConnectionClient {
	return &clientConnectionClient{cc}
}

func (c *clientConnectionClient) RequestConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionReply, error) {
	out := new(ConnectionReply)
	err := c.cc.Invoke(ctx, "/nsmconnect.ClientConnection/RequestConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ClientConnection service

type ClientConnectionServer interface {
	RequestConnection(context.Context, *ConnectionRequest) (*ConnectionReply, error)
}

func RegisterClientConnectionServer(s *grpc.Server, srv ClientConnectionServer) {
	s.RegisterService(&_ClientConnection_serviceDesc, srv)
}

func _ClientConnection_RequestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientConnectionServer).RequestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nsmconnect.ClientConnection/RequestConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientConnectionServer).RequestConnection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientConnection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nsmconnect.ClientConnection",
	HandlerType: (*ClientConnectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestConnection",
			Handler:    _ClientConnection_RequestConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nsmconnect.proto",
}

func init() { proto.RegisterFile("nsmconnect.proto", fileDescriptor_nsmconnect_e1d5841ad497266e) }

var fileDescriptor_nsmconnect_e1d5841ad497266e = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x95, 0x57, 0x40, 0xeb, 0x37, 0x69, 0xeb, 0xac, 0x80, 0x42, 0xd0, 0xa4, 0xaa, 0x37, 0xec,
	0x2a, 0x41, 0x85, 0x0b, 0xb4, 0xdb, 0xa9, 0x42, 0x48, 0x30, 0x50, 0x10, 0xd7, 0x91, 0xe7, 0x7e,
	0xb4, 0x56, 0xe3, 0x1f, 0x6c, 0x67, 0x90, 0xe7, 0xe3, 0x05, 0x78, 0x07, 0x5e, 0x04, 0x25, 0xf1,
	0x92, 0x0a, 0xa5, 0x62, 0x57, 0xb1, 0xcf, 0x39, 0x39, 0xf6, 0x77, 0x8e, 0x61, 0xa6, 0x9c, 0xe4,
	0x5a, 0x29, 0xe4, 0x3e, 0x35, 0x56, 0x7b, 0x4d, 0x61, 0x40, 0x92, 0xd5, 0x46, 0xf8, 0x6d, 0x75,
	0x9b, 0x72, 0x2d, 0xb3, 0x52, 0x6c, 0x98, 0xd7, 0x99, 0x42, 0xff, 0x43, 0xdb, 0x9d, 0x43, 0x7b,
	0x27, 0x38, 0x4a, 0x74, 0xdb, 0xcc, 0xec, 0x36, 0x99, 0x72, 0x32, 0x63, 0x46, 0xb8, 0x8c, 0x6b,
	0x29, 0xb5, 0x0a, 0x9f, 0xce, 0x72, 0xf1, 0x8b, 0xc0, 0xf9, 0x75, 0x67, 0x29, 0xb4, 0xca, 0xf1,
	0x7b, 0x85, 0xce, 0xd3, 0x0b, 0x00, 0xdb, 0x2d, 0x0b, 0xb1, 0x8e, 0xc9, 0x9c, 0x5c, 0x4e, 0xf3,
	0x69, 0x40, 0xde, 0xaf, 0xe9, 0x2b, 0x88, 0xc2, 0x59, 0x45, 0x38, 0xac, 0x50, 0x4c, 0x62, 0x7c,
	0xd4, 0x0a, 0x69, 0xe0, 0xbe, 0x74, 0xd4, 0x0d, 0x93, 0x48, 0x5f, 0xc2, 0x59, 0x29, 0x54, 0xf5,
	0xb3, 0xd5, 0x39, 0xc3, 0x38, 0xc6, 0x93, 0x56, 0x7c, 0xda, 0xc2, 0x37, 0xf7, 0x28, 0x7d, 0x03,
	0x53, 0xa1, 0x3c, 0xda, 0x6f, 0x8d, 0xe4, 0xd1, 0x7c, 0x72, 0x79, 0xb2, 0x7c, 0x96, 0x86, 0x1b,
	0x7f, 0xd0, 0x9c, 0x95, 0x1f, 0x91, 0x6f, 0x99, 0x12, 0x4e, 0xe6, 0x83, 0x70, 0xf1, 0x9b, 0x40,
	0x34, 0x4c, 0xf1, 0x99, 0x59, 0x26, 0xd1, 0xa3, 0x75, 0x54, 0xc3, 0x53, 0xde, 0xe3, 0x85, 0xe9,
	0x89, 0x98, 0xb4, 0xd6, 0x57, 0xe9, 0x5e, 0xc6, 0x63, 0x06, 0xa3, 0xe0, 0x4a, 0x79, 0x5b, 0xe7,
	0x11, 0x1f, 0xa1, 0x92, 0x77, 0xf0, 0xfc, 0xe0, 0x2f, 0x74, 0x06, 0x93, 0x1d, 0xd6, 0x21, 0xcf,
	0x66, 0x49, 0x23, 0x78, 0x7c, 0xc7, 0xca, 0xea, 0x3e, 0xba, 0x6e, 0x73, 0x75, 0xf4, 0x96, 0x2c,
	0xfe, 0x10, 0x38, 0xdb, 0x2f, 0xc6, 0x94, 0x35, 0x4d, 0xe0, 0x98, 0x71, 0x8e, 0xc6, 0x63, 0x57,
	0xca, 0x71, 0xde, 0xef, 0x9b, 0x84, 0xd9, 0x5a, 0x0a, 0xe7, 0x9a, 0x41, 0xd1, 0x5a, 0x6d, 0x83,
	0xe7, 0x69, 0x0f, 0xaf, 0x1a, 0x94, 0x7e, 0x3d, 0x14, 0x49, 0x53, 0xc8, 0xc9, 0x72, 0xfe, 0xbf,
	0x48, 0xc6, 0x07, 0xff, 0xb7, 0x38, 0xf2, 0xa0, 0xe2, 0x96, 0x1c, 0x66, 0xd7, 0xa5, 0x40, 0xe5,
	0x87, 0x93, 0xe8, 0x27, 0x38, 0x0f, 0xef, 0x70, 0x0f, 0xbc, 0x18, 0xbf, 0x56, 0x10, 0x26, 0x2f,
	0x0e, 0xd1, 0xa6, 0xac, 0x6f, 0x9f, 0xb4, 0x4f, 0xfd, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0x55, 0xef, 0x99, 0x51, 0x03, 0x00, 0x00,
}
