// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataplane.proto

package dataplane

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	crossconnect "github.com/networkservicemesh/networkservicemesh/controlplane/api/crossconnect"
	connection1 "github.com/networkservicemesh/networkservicemesh/controlplane/api/local/connection"
	connection "github.com/networkservicemesh/networkservicemesh/controlplane/api/remote/connection"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message sent by dataplane module informing NSM of any changes in its
// operations parameters or constraints
type MechanismUpdate struct {
	RemoteMechanisms     []*connection.Mechanism  `protobuf:"bytes,1,rep,name=remote_mechanisms,json=remoteMechanisms,proto3" json:"remote_mechanisms,omitempty"`
	LocalMechanisms      []*connection1.Mechanism `protobuf:"bytes,2,rep,name=local_mechanisms,json=localMechanisms,proto3" json:"local_mechanisms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MechanismUpdate) Reset()         { *m = MechanismUpdate{} }
func (m *MechanismUpdate) String() string { return proto.CompactTextString(m) }
func (*MechanismUpdate) ProtoMessage()    {}
func (*MechanismUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_617387e490a04ffa, []int{0}
}

func (m *MechanismUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MechanismUpdate.Unmarshal(m, b)
}
func (m *MechanismUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MechanismUpdate.Marshal(b, m, deterministic)
}
func (m *MechanismUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MechanismUpdate.Merge(m, src)
}
func (m *MechanismUpdate) XXX_Size() int {
	return xxx_messageInfo_MechanismUpdate.Size(m)
}
func (m *MechanismUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MechanismUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MechanismUpdate proto.InternalMessageInfo

func (m *MechanismUpdate) GetRemoteMechanisms() []*connection.Mechanism {
	if m != nil {
		return m.RemoteMechanisms
	}
	return nil
}

func (m *MechanismUpdate) GetLocalMechanisms() []*connection1.Mechanism {
	if m != nil {
		return m.LocalMechanisms
	}
	return nil
}

type CrossConnectList struct {
	Source               []*crossconnect.CrossConnect `protobuf:"bytes,1,rep,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CrossConnectList) Reset()         { *m = CrossConnectList{} }
func (m *CrossConnectList) String() string { return proto.CompactTextString(m) }
func (*CrossConnectList) ProtoMessage()    {}
func (*CrossConnectList) Descriptor() ([]byte, []int) {
	return fileDescriptor_617387e490a04ffa, []int{1}
}

func (m *CrossConnectList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrossConnectList.Unmarshal(m, b)
}
func (m *CrossConnectList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrossConnectList.Marshal(b, m, deterministic)
}
func (m *CrossConnectList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrossConnectList.Merge(m, src)
}
func (m *CrossConnectList) XXX_Size() int {
	return xxx_messageInfo_CrossConnectList.Size(m)
}
func (m *CrossConnectList) XXX_DiscardUnknown() {
	xxx_messageInfo_CrossConnectList.DiscardUnknown(m)
}

var xxx_messageInfo_CrossConnectList proto.InternalMessageInfo

func (m *CrossConnectList) GetSource() []*crossconnect.CrossConnect {
	if m != nil {
		return m.Source
	}
	return nil
}

func init() {
	proto.RegisterType((*MechanismUpdate)(nil), "dataplane.MechanismUpdate")
	proto.RegisterType((*CrossConnectList)(nil), "dataplane.CrossConnectList")
}

func init() { proto.RegisterFile("dataplane.proto", fileDescriptor_617387e490a04ffa) }

var fileDescriptor_617387e490a04ffa = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x3d, 0x6f, 0xea, 0x30,
	0x14, 0x55, 0xde, 0xd3, 0xe3, 0x09, 0x77, 0x00, 0x3c, 0x54, 0x28, 0x74, 0xa8, 0x98, 0x3a, 0x39,
	0x55, 0x3a, 0x76, 0x42, 0x14, 0xa4, 0x4a, 0x65, 0x41, 0xea, 0xda, 0xca, 0x31, 0xb7, 0x60, 0xd5,
	0xc9, 0x75, 0x6d, 0x87, 0x8a, 0xff, 0xd3, 0x5f, 0xd4, 0x5f, 0x54, 0x25, 0x0e, 0x10, 0x10, 0xcd,
	0xc2, 0x12, 0x39, 0xf7, 0xdc, 0x7b, 0xce, 0xfd, 0x38, 0xa4, 0xb3, 0xe0, 0x8e, 0x6b, 0xc5, 0x33,
	0x60, 0xda, 0xa0, 0x43, 0xda, 0xde, 0x05, 0x42, 0xb1, 0x94, 0x6e, 0x95, 0x27, 0x4c, 0x60, 0x1a,
	0x65, 0xe0, 0x3e, 0xd1, 0xbc, 0x5b, 0x30, 0x6b, 0x29, 0x20, 0x05, 0xbb, 0x3a, 0x15, 0x12, 0x98,
	0x39, 0x83, 0xaa, 0x2c, 0x8f, 0xb8, 0x96, 0x91, 0x42, 0xc1, 0x55, 0x11, 0xce, 0x40, 0x38, 0x89,
	0x59, 0xed, 0xe9, 0xf5, 0xc2, 0xc5, 0xf9, 0x22, 0x06, 0x52, 0x74, 0xd0, 0xa8, 0xc2, 0xcf, 0x57,
	0x11, 0x06, 0xad, 0xad, 0x88, 0x0f, 0x7e, 0x2a, 0x89, 0xbe, 0x76, 0x1b, 0x0d, 0x36, 0x82, 0x54,
	0xbb, 0x8d, 0xff, 0x7a, 0x64, 0xf8, 0x15, 0x90, 0xce, 0x0c, 0xc4, 0x8a, 0x67, 0xd2, 0xa6, 0xcf,
	0x7a, 0xc1, 0x1d, 0xd0, 0x47, 0xd2, 0xf3, 0x6d, 0xbf, 0xa6, 0x5b, 0xc4, 0xf6, 0x83, 0xeb, 0xbf,
	0x37, 0x17, 0xf1, 0x15, 0xf3, 0x08, 0xab, 0x4d, 0xb1, 0x2b, 0x9f, 0x77, 0x3d, 0xb8, 0x0b, 0x58,
	0x3a, 0x25, 0xdd, 0x72, 0xcd, 0x75, 0xa6, 0x3f, 0x25, 0xd3, 0x80, 0x95, 0xc0, 0x69, 0xa2, 0x4e,
	0x89, 0xed, 0x79, 0x86, 0x53, 0xd2, 0x1d, 0x17, 0x63, 0x8d, 0x7d, 0xf6, 0x93, 0xb4, 0x8e, 0xc6,
	0xa4, 0x65, 0x31, 0x37, 0x02, 0xaa, 0xde, 0x42, 0x76, 0x30, 0x79, 0x3d, 0x7f, 0x5e, 0x65, 0xc6,
	0xdf, 0x01, 0x69, 0x3f, 0x6c, 0x4d, 0x44, 0x47, 0xe4, 0xff, 0x1c, 0x3e, 0x72, 0xb0, 0x8e, 0x36,
	0x14, 0x87, 0x0d, 0x18, 0xbd, 0x27, 0xff, 0xc6, 0x0a, 0x2d, 0x34, 0x12, 0x5c, 0xb2, 0x25, 0xe2,
	0x52, 0x55, 0x36, 0x4e, 0xf2, 0x37, 0x36, 0x29, 0x4e, 0x40, 0x27, 0xa4, 0x3d, 0x5a, 0x73, 0xa9,
	0x78, 0xa2, 0x80, 0x0e, 0xd8, 0xde, 0xee, 0xc7, 0xb3, 0x86, 0x4d, 0x60, 0xfc, 0x42, 0x7a, 0xfb,
	0x55, 0xcd, 0x30, 0x93, 0x0e, 0x4d, 0x71, 0xc4, 0xea, 0x59, 0x3b, 0xc7, 0x2f, 0x8d, 0x84, 0x61,
	0x8d, 0xfe, 0xc8, 0x0d, 0xb7, 0x41, 0xd2, 0x2a, 0xb3, 0xef, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x43, 0xb7, 0x2f, 0xc7, 0x90, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataplaneClient is the client API for Dataplane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataplaneClient interface {
	Request(ctx context.Context, in *crossconnect.CrossConnect, opts ...grpc.CallOption) (*crossconnect.CrossConnect, error)
	Close(ctx context.Context, in *crossconnect.CrossConnect, opts ...grpc.CallOption) (*empty.Empty, error)
	Available(ctx context.Context, in *CrossConnectList, opts ...grpc.CallOption) (*CrossConnectList, error)
}

type dataplaneClient struct {
	cc *grpc.ClientConn
}

func NewDataplaneClient(cc *grpc.ClientConn) DataplaneClient {
	return &dataplaneClient{cc}
}

func (c *dataplaneClient) Request(ctx context.Context, in *crossconnect.CrossConnect, opts ...grpc.CallOption) (*crossconnect.CrossConnect, error) {
	out := new(crossconnect.CrossConnect)
	err := c.cc.Invoke(ctx, "/dataplane.Dataplane/Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneClient) Close(ctx context.Context, in *crossconnect.CrossConnect, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dataplane.Dataplane/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneClient) Available(ctx context.Context, in *CrossConnectList, opts ...grpc.CallOption) (*CrossConnectList, error) {
	out := new(CrossConnectList)
	err := c.cc.Invoke(ctx, "/dataplane.Dataplane/Available", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneServer is the server API for Dataplane service.
type DataplaneServer interface {
	Request(context.Context, *crossconnect.CrossConnect) (*crossconnect.CrossConnect, error)
	Close(context.Context, *crossconnect.CrossConnect) (*empty.Empty, error)
	Available(context.Context, *CrossConnectList) (*CrossConnectList, error)
}

// UnimplementedDataplaneServer can be embedded to have forward compatible implementations.
type UnimplementedDataplaneServer struct {
}

func (*UnimplementedDataplaneServer) Request(ctx context.Context, req *crossconnect.CrossConnect) (*crossconnect.CrossConnect, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (*UnimplementedDataplaneServer) Close(ctx context.Context, req *crossconnect.CrossConnect) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedDataplaneServer) Available(ctx context.Context, req *CrossConnectList) (*CrossConnectList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Available not implemented")
}

func RegisterDataplaneServer(s *grpc.Server, srv DataplaneServer) {
	s.RegisterService(&_Dataplane_serviceDesc, srv)
}

func _Dataplane_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(crossconnect.CrossConnect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataplane.Dataplane/Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServer).Request(ctx, req.(*crossconnect.CrossConnect))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dataplane_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(crossconnect.CrossConnect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataplane.Dataplane/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServer).Close(ctx, req.(*crossconnect.CrossConnect))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dataplane_Available_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossConnectList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServer).Available(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dataplane.Dataplane/Available",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServer).Available(ctx, req.(*CrossConnectList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dataplane_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.Dataplane",
	HandlerType: (*DataplaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _Dataplane_Request_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Dataplane_Close_Handler,
		},
		{
			MethodName: "Available",
			Handler:    _Dataplane_Available_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dataplane.proto",
}

// MechanismsMonitorClient is the client API for MechanismsMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MechanismsMonitorClient interface {
	MonitorMechanisms(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MechanismsMonitor_MonitorMechanismsClient, error)
}

type mechanismsMonitorClient struct {
	cc *grpc.ClientConn
}

func NewMechanismsMonitorClient(cc *grpc.ClientConn) MechanismsMonitorClient {
	return &mechanismsMonitorClient{cc}
}

func (c *mechanismsMonitorClient) MonitorMechanisms(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MechanismsMonitor_MonitorMechanismsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MechanismsMonitor_serviceDesc.Streams[0], "/dataplane.MechanismsMonitor/MonitorMechanisms", opts...)
	if err != nil {
		return nil, err
	}
	x := &mechanismsMonitorMonitorMechanismsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MechanismsMonitor_MonitorMechanismsClient interface {
	Recv() (*MechanismUpdate, error)
	grpc.ClientStream
}

type mechanismsMonitorMonitorMechanismsClient struct {
	grpc.ClientStream
}

func (x *mechanismsMonitorMonitorMechanismsClient) Recv() (*MechanismUpdate, error) {
	m := new(MechanismUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MechanismsMonitorServer is the server API for MechanismsMonitor service.
type MechanismsMonitorServer interface {
	MonitorMechanisms(*empty.Empty, MechanismsMonitor_MonitorMechanismsServer) error
}

// UnimplementedMechanismsMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedMechanismsMonitorServer struct {
}

func (*UnimplementedMechanismsMonitorServer) MonitorMechanisms(req *empty.Empty, srv MechanismsMonitor_MonitorMechanismsServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitorMechanisms not implemented")
}

func RegisterMechanismsMonitorServer(s *grpc.Server, srv MechanismsMonitorServer) {
	s.RegisterService(&_MechanismsMonitor_serviceDesc, srv)
}

func _MechanismsMonitor_MonitorMechanisms_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MechanismsMonitorServer).MonitorMechanisms(m, &mechanismsMonitorMonitorMechanismsServer{stream})
}

type MechanismsMonitor_MonitorMechanismsServer interface {
	Send(*MechanismUpdate) error
	grpc.ServerStream
}

type mechanismsMonitorMonitorMechanismsServer struct {
	grpc.ServerStream
}

func (x *mechanismsMonitorMonitorMechanismsServer) Send(m *MechanismUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _MechanismsMonitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.MechanismsMonitor",
	HandlerType: (*MechanismsMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorMechanisms",
			Handler:       _MechanismsMonitor_MonitorMechanisms_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dataplane.proto",
}
