---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: pull-builder
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull ${_REPO}/${_NAME}-${_TARGET}:${_CACHE_TAG} || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    id: pull-image
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull ${_REPO}/${_NAME}:${_CACHE_TAG} || exit 0
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: build-builder
    args: [
      'build',
      '-t',
      '${_REPO}/${_NAME}-${_TARGET}:${_TAG}',
      '--target',
      'build',
      '--cache-from',
      '${_REPO}/${_NAME}-${_TARGET}:${_CACHE_TAG}',
      '-f',
      'docker/Dockerfile.${_NAME}',
      '.'
    ]
    waitFor:
      - pull-builder
  - name: 'gcr.io/cloud-builders/docker'
    id: build-image
    args: [
      'build',
      '--build-arg', 'VPP_AGENT=${_VPP_AGENT}',
      '--build-arg', 'VPP_DEV=${_VPP_AGENT_DEV}',
      '--build-arg', 'REPO=${_REPO}',
      '-t',
      '${_REPO}/${_NAME}:${_TAG}',
      '--cache-from',
      '${_REPO}/${_NAME}:${_CACHE_TAG}',
      '--cache-from',
      '${_REPO}/${_NAME}-${_TARGET}:${_CACHE_TAG}',
      '-f',
      'docker/Dockerfile.${_NAME}',
      '.'
    ]
    waitFor:
      - pull-builder
      - pull-image

images: [
  '${_REPO}/${_NAME}-${_TARGET}:${_TAG}',
  '${_REPO}/${_NAME}:${_TAG}'
]

substitutions:
  _TAG: latest
  _CACHE_TAG: latest
  _REPO: gcr.io/PROJECT
  _NAME: nsmd
  _TARGET: build
  _VPP_AGENT: vpp_agent
  _VPP_AGENT_DEV: vpp_agent_dev
