// Code generated by protoc-gen-go. DO NOT EDIT.
// source: netmesh.proto

package netmesh

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/ligato/networkservicemesh/pkg/nsm/apis/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkServiceEndpoint struct {
	NetworkServiceName   string              `protobuf:"bytes,1,opt,name=network_service_name,json=networkServiceName,proto3" json:"network_service_name,omitempty"`
	NetworkServiceHost   string              `protobuf:"bytes,2,opt,name=network_service_host,json=networkServiceHost,proto3" json:"network_service_host,omitempty"`
	NseProviderName      string              `protobuf:"bytes,3,opt,name=nse_provider_name,json=nseProviderName,proto3" json:"nse_provider_name,omitempty"`
	NseProviderNamespace string              `protobuf:"bytes,4,opt,name=nse_provider_namespace,json=nseProviderNamespace,proto3" json:"nse_provider_namespace,omitempty"`
	SocketLocation       string              `protobuf:"bytes,5,opt,name=socket_location,json=socketLocation,proto3" json:"socket_location,omitempty"`
	Interface            []*common.Interface `protobuf:"bytes,6,rep,name=interface,proto3" json:"interface,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetworkServiceEndpoint) Reset()         { *m = NetworkServiceEndpoint{} }
func (m *NetworkServiceEndpoint) String() string { return proto.CompactTextString(m) }
func (*NetworkServiceEndpoint) ProtoMessage()    {}
func (*NetworkServiceEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_netmesh_1d13a136d00f744f, []int{0}
}
func (m *NetworkServiceEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkServiceEndpoint.Unmarshal(m, b)
}
func (m *NetworkServiceEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkServiceEndpoint.Marshal(b, m, deterministic)
}
func (dst *NetworkServiceEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkServiceEndpoint.Merge(dst, src)
}
func (m *NetworkServiceEndpoint) XXX_Size() int {
	return xxx_messageInfo_NetworkServiceEndpoint.Size(m)
}
func (m *NetworkServiceEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkServiceEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkServiceEndpoint proto.InternalMessageInfo

func (m *NetworkServiceEndpoint) GetNetworkServiceName() string {
	if m != nil {
		return m.NetworkServiceName
	}
	return ""
}

func (m *NetworkServiceEndpoint) GetNetworkServiceHost() string {
	if m != nil {
		return m.NetworkServiceHost
	}
	return ""
}

func (m *NetworkServiceEndpoint) GetNseProviderName() string {
	if m != nil {
		return m.NseProviderName
	}
	return ""
}

func (m *NetworkServiceEndpoint) GetNseProviderNamespace() string {
	if m != nil {
		return m.NseProviderNamespace
	}
	return ""
}

func (m *NetworkServiceEndpoint) GetSocketLocation() string {
	if m != nil {
		return m.SocketLocation
	}
	return ""
}

func (m *NetworkServiceEndpoint) GetInterface() []*common.Interface {
	if m != nil {
		return m.Interface
	}
	return nil
}

type NetworkService struct {
	NetworkServiceName   string   `protobuf:"bytes,1,opt,name=network_service_name,json=networkServiceName,proto3" json:"network_service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkService) Reset()         { *m = NetworkService{} }
func (m *NetworkService) String() string { return proto.CompactTextString(m) }
func (*NetworkService) ProtoMessage()    {}
func (*NetworkService) Descriptor() ([]byte, []int) {
	return fileDescriptor_netmesh_1d13a136d00f744f, []int{1}
}
func (m *NetworkService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkService.Unmarshal(m, b)
}
func (m *NetworkService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkService.Marshal(b, m, deterministic)
}
func (dst *NetworkService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkService.Merge(dst, src)
}
func (m *NetworkService) XXX_Size() int {
	return xxx_messageInfo_NetworkService.Size(m)
}
func (m *NetworkService) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkService.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkService proto.InternalMessageInfo

func (m *NetworkService) GetNetworkServiceName() string {
	if m != nil {
		return m.NetworkServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkServiceEndpoint)(nil), "netmesh.NetworkServiceEndpoint")
	proto.RegisterType((*NetworkService)(nil), "netmesh.NetworkService")
}

func init() { proto.RegisterFile("netmesh.proto", fileDescriptor_netmesh_1d13a136d00f744f) }

var fileDescriptor_netmesh_1d13a136d00f744f = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xd1, 0x4a, 0x82, 0x31,
	0x14, 0xc7, 0x51, 0xcb, 0x70, 0x91, 0xe2, 0x10, 0xf9, 0xe8, 0x4a, 0xbc, 0x49, 0xba, 0x70, 0x51,
	0x3d, 0x41, 0x20, 0x14, 0x84, 0x84, 0x3d, 0xc0, 0xc7, 0x9c, 0x27, 0x1d, 0x9f, 0x3b, 0x67, 0x6c,
	0x27, 0x7b, 0xb5, 0x1e, 0x2f, 0xdc, 0xb7, 0x08, 0xcb, 0x9b, 0xae, 0xc6, 0xce, 0xf9, 0xff, 0x7e,
	0x83, 0xff, 0xc4, 0x05, 0x02, 0x3b, 0x88, 0x9b, 0xa9, 0x0f, 0xc4, 0x24, 0xcf, 0xf2, 0xf5, 0x72,
	0xb6, 0xb6, 0xbc, 0x79, 0x5f, 0x4e, 0x0d, 0x39, 0xb5, 0xb5, 0x6b, 0xcd, 0xa4, 0x10, 0xf8, 0x83,
	0x42, 0x15, 0x21, 0xec, 0xac, 0x81, 0x7d, 0x4a, 0xf9, 0x6a, 0xad, 0x30, 0x3a, 0xa5, 0xbd, 0x8d,
	0xca, 0x90, 0x73, 0x84, 0xf9, 0xa8, 0x7d, 0xe3, 0xcf, 0xa6, 0x18, 0xce, 0x6b, 0xee, 0xb5, 0xe6,
	0x66, 0xb8, 0xf2, 0x64, 0x91, 0xe5, 0x8d, 0x18, 0x64, 0x63, 0x99, 0x95, 0x25, 0x6a, 0x07, 0x45,
	0x63, 0xd4, 0x98, 0x74, 0x16, 0x12, 0x0f, 0xa8, 0xb9, 0x76, 0x70, 0x8c, 0xd8, 0x50, 0xe4, 0xa2,
	0x79, 0x8c, 0x78, 0xa4, 0xc8, 0xf2, 0x5a, 0xf4, 0x31, 0x42, 0xe9, 0x03, 0xed, 0xec, 0x0a, 0x42,
	0xfd, 0x40, 0x2b, 0xc5, 0x7b, 0x18, 0xe1, 0x25, 0xcf, 0x93, 0xfd, 0x5e, 0x0c, 0xff, 0x64, 0xa3,
	0xd7, 0x06, 0x8a, 0x93, 0x04, 0x0c, 0x7e, 0x01, 0x69, 0x27, 0xaf, 0x44, 0x2f, 0x92, 0xa9, 0x80,
	0xcb, 0x2d, 0x19, 0xcd, 0x96, 0xb0, 0x38, 0x4d, 0xf1, 0x6e, 0x3d, 0x7e, 0xce, 0x53, 0xa9, 0x44,
	0xc7, 0x22, 0x43, 0x78, 0xdb, 0x1b, 0xdb, 0xa3, 0xd6, 0xe4, 0xfc, 0xb6, 0x3f, 0xcd, 0x5d, 0x3d,
	0x7d, 0x2f, 0x16, 0x3f, 0x99, 0xf1, 0x83, 0xe8, 0x1e, 0x36, 0xf7, 0xff, 0xc6, 0x96, 0xed, 0xf4,
	0x0b, 0x77, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0x02, 0x1c, 0x58, 0xe6, 0x01, 0x00, 0x00,
}
