# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../..", "/go/src/github.com/ligato/networkservicemesh"

  config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
  end
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provision "shell", inline: <<-EOC
    apt-get update -qq -y
  EOC

  # If you need hugepages, this is how you get them
  # config.vm.provision "shell", path: "scripts/setup_hugepages.sh"
  config.vm.provision "shell", path: "scripts/install_docker.sh"
  config.vm.provision "shell", path: "scripts/install_kubernetes.sh"
  config.vm.provision "shell", path: "scripts/load_images.sh"
  config.vm.provision "shell", inline: "sudo usermod -a -G docker vagrant"
  config.vm.provision "shell", inline: "mkdir -p /var/lib/networkservicemesh"
  config.vm.define "master" do |master|
    master.vm.hostname = "kube-master"
    master.vm.provision "shell", path: "scripts/configureK8smaster.sh"
  end
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "kube-worker"
    worker.vm.provision "shell", path: "scripts/configureK8sworker.sh"
  end

end
